-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_filter is
generic (
    C_S_AXI_CONTROL_BUS_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_CONTROL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_CONTROL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CONTROL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CONTROL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CONTROL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CONTROL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    video_in_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    video_in_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    video_in_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    video_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    video_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    video_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    video_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    video_out_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    video_out_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    video_out_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_in_TVALID : IN STD_LOGIC;
    video_in_TREADY : OUT STD_LOGIC;
    video_out_TVALID : OUT STD_LOGIC;
    video_out_TREADY : IN STD_LOGIC );
end;


architecture behav of image_filter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "image_filter,hls_ip_2014_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=6.666670,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.810000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=3,HLS_SYN_DSP=17,HLS_SYN_FF=2151,HLS_SYN_LUT=2695}";
    constant C_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_true : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";

    signal ap_rst_n_inv : STD_LOGIC;
    signal image_filter_CONTROL_BUS_s_axi_U_ap_dummy_ce : STD_LOGIC;
    signal rows : STD_LOGIC_VECTOR (31 downto 0);
    signal cols : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal C_XR0C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_XR0C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_XR0C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_XR1C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_XR1C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_XR1C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_XR2C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_XR2C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_XR2C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_YR0C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_YR0C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_YR0C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_YR1C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_YR1C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_YR1C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_YR2C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_YR2C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_YR2C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_high_thresh : STD_LOGIC_VECTOR (31 downto 0);
    signal c_low_thresh : STD_LOGIC_VECTOR (31 downto 0);
    signal c_invert : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_Block_proc_U0_ap_start : STD_LOGIC;
    signal image_filter_Block_proc_U0_ap_done : STD_LOGIC;
    signal image_filter_Block_proc_U0_ap_continue : STD_LOGIC;
    signal image_filter_Block_proc_U0_ap_idle : STD_LOGIC;
    signal image_filter_Block_proc_U0_ap_ready : STD_LOGIC;
    signal image_filter_Block_proc_U0_rows : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_Block_proc_U0_cols : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_Block_proc_U0_ap_return_0 : STD_LOGIC_VECTOR (11 downto 0);
    signal image_filter_Block_proc_U0_ap_return_1 : STD_LOGIC_VECTOR (11 downto 0);
    signal image_filter_Block_proc_U0_ap_return_2 : STD_LOGIC_VECTOR (11 downto 0);
    signal image_filter_Block_proc_U0_ap_return_3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel : STD_LOGIC;
    signal img_0_rows_V_channel_full_n : STD_LOGIC;
    signal ap_reg_ready_img_0_rows_V_channel_full_n : STD_LOGIC := '0';
    signal ap_sig_ready_img_0_rows_V_channel_full_n : STD_LOGIC;
    signal ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel : STD_LOGIC;
    signal img_0_cols_V_channel_full_n : STD_LOGIC;
    signal ap_reg_ready_img_0_cols_V_channel_full_n : STD_LOGIC := '0';
    signal ap_sig_ready_img_0_cols_V_channel_full_n : STD_LOGIC;
    signal ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V : STD_LOGIC;
    signal img_1_rows_V_full_n : STD_LOGIC;
    signal ap_reg_ready_img_1_rows_V_full_n : STD_LOGIC := '0';
    signal ap_sig_ready_img_1_rows_V_full_n : STD_LOGIC;
    signal ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V : STD_LOGIC;
    signal img_1_cols_V_full_n : STD_LOGIC;
    signal ap_reg_ready_img_1_cols_V_full_n : STD_LOGIC := '0';
    signal ap_sig_ready_img_1_cols_V_full_n : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_ap_start : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_ap_done : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_ap_continue : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_ap_idle : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_ap_ready : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_video_in_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal image_filter_AXIvideo2Mat_U0_video_in_TVALID : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_video_in_TREADY : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_video_in_TKEEP : STD_LOGIC_VECTOR (1 downto 0);
    signal image_filter_AXIvideo2Mat_U0_video_in_TSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal image_filter_AXIvideo2Mat_U0_video_in_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal image_filter_AXIvideo2Mat_U0_video_in_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal image_filter_AXIvideo2Mat_U0_video_in_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal image_filter_AXIvideo2Mat_U0_video_in_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal image_filter_AXIvideo2Mat_U0_img_rows_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal image_filter_AXIvideo2Mat_U0_img_cols_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n : STD_LOGIC;
    signal image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_ap_start : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_ap_done : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_ap_continue : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_ap_idle : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_ap_ready : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_src_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal image_filter_sobel_filter_core_U0_src_data_stream_0_V_empty_n : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_src_data_stream_0_V_read : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_src_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal image_filter_sobel_filter_core_U0_src_data_stream_1_V_empty_n : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_src_data_stream_1_V_read : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_dst_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal image_filter_sobel_filter_core_U0_dst_data_stream_0_V_full_n : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_dst_data_stream_0_V_write : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_dst_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal image_filter_sobel_filter_core_U0_dst_data_stream_1_V_full_n : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_dst_data_stream_1_V_write : STD_LOGIC;
    signal image_filter_sobel_filter_core_U0_rows : STD_LOGIC_VECTOR (10 downto 0);
    signal image_filter_sobel_filter_core_U0_cols : STD_LOGIC_VECTOR (10 downto 0);
    signal image_filter_sobel_filter_core_U0_C_XR0C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_XR0C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_XR0C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_XR1C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_XR1C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_XR1C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_XR2C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_XR2C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_XR2C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_YR0C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_YR0C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_YR0C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_YR1C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_YR1C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_YR1C2 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_YR2C0 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_C_YR2C1 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_c_high_thresh : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_c_low_thresh : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_sobel_filter_core_U0_c_invert : STD_LOGIC_VECTOR (31 downto 0);
    signal image_filter_Mat2AXIvideo_U0_ap_start : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_ap_done : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_ap_continue : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_ap_idle : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_ap_ready : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_img_rows_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal image_filter_Mat2AXIvideo_U0_img_cols_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_read : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_read : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_video_out_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal image_filter_Mat2AXIvideo_U0_video_out_TVALID : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_video_out_TREADY : STD_LOGIC;
    signal image_filter_Mat2AXIvideo_U0_video_out_TKEEP : STD_LOGIC_VECTOR (1 downto 0);
    signal image_filter_Mat2AXIvideo_U0_video_out_TSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal image_filter_Mat2AXIvideo_U0_video_out_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal image_filter_Mat2AXIvideo_U0_video_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal image_filter_Mat2AXIvideo_U0_video_out_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal image_filter_Mat2AXIvideo_U0_video_out_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_hs_continue : STD_LOGIC;
    signal img_0_rows_V_channel_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_rows_V_channel_din : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_rows_V_channel_write : STD_LOGIC;
    signal img_0_rows_V_channel_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_rows_V_channel_empty_n : STD_LOGIC;
    signal img_0_rows_V_channel_read : STD_LOGIC;
    signal img_0_cols_V_channel_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_cols_V_channel_din : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_cols_V_channel_write : STD_LOGIC;
    signal img_0_cols_V_channel_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_cols_V_channel_empty_n : STD_LOGIC;
    signal img_0_cols_V_channel_read : STD_LOGIC;
    signal img_1_rows_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_1_rows_V_din : STD_LOGIC_VECTOR (11 downto 0);
    signal img_1_rows_V_write : STD_LOGIC;
    signal img_1_rows_V_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal img_1_rows_V_empty_n : STD_LOGIC;
    signal img_1_rows_V_read : STD_LOGIC;
    signal img_1_cols_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_1_cols_V_din : STD_LOGIC_VECTOR (11 downto 0);
    signal img_1_cols_V_write : STD_LOGIC;
    signal img_1_cols_V_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal img_1_cols_V_empty_n : STD_LOGIC;
    signal img_1_cols_V_read : STD_LOGIC;
    signal img_0_data_stream_0_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_0_V_full_n : STD_LOGIC;
    signal img_0_data_stream_0_V_write : STD_LOGIC;
    signal img_0_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_0_V_empty_n : STD_LOGIC;
    signal img_0_data_stream_0_V_read : STD_LOGIC;
    signal img_0_data_stream_1_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_1_V_full_n : STD_LOGIC;
    signal img_0_data_stream_1_V_write : STD_LOGIC;
    signal img_0_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_1_V_empty_n : STD_LOGIC;
    signal img_0_data_stream_1_V_read : STD_LOGIC;
    signal img_1_data_stream_0_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_1_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_0_V_full_n : STD_LOGIC;
    signal img_1_data_stream_0_V_write : STD_LOGIC;
    signal img_1_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_0_V_empty_n : STD_LOGIC;
    signal img_1_data_stream_0_V_read : STD_LOGIC;
    signal img_1_data_stream_1_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_1_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_1_V_full_n : STD_LOGIC;
    signal img_1_data_stream_1_V_write : STD_LOGIC;
    signal img_1_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_1_V_empty_n : STD_LOGIC;
    signal img_1_data_stream_1_V_read : STD_LOGIC;
    signal ap_reg_procdone_image_filter_Block_proc_U0 : STD_LOGIC := '0';
    signal ap_sig_hs_done : STD_LOGIC;
    signal ap_reg_procdone_image_filter_AXIvideo2Mat_U0 : STD_LOGIC := '0';
    signal ap_reg_procdone_image_filter_sobel_filter_core_U0 : STD_LOGIC := '0';
    signal ap_reg_procdone_image_filter_Mat2AXIvideo_U0 : STD_LOGIC := '0';
    signal ap_CS : STD_LOGIC;
    signal ap_sig_top_allready : STD_LOGIC;
    signal ap_reg_ready_image_filter_Block_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sig_ready_image_filter_Block_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sig_start_in_image_filter_Block_proc_U0_ap_start : STD_LOGIC;
    signal ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready : STD_LOGIC;
    signal ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start : STD_LOGIC;
    signal ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready : STD_LOGIC;
    signal ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start : STD_LOGIC;

    component image_filter_Block_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rows : IN STD_LOGIC_VECTOR (31 downto 0);
        cols : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component image_filter_AXIvideo2Mat IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        video_in_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        video_in_TVALID : IN STD_LOGIC;
        video_in_TREADY : OUT STD_LOGIC;
        video_in_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
        video_in_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
        video_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        video_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        video_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        video_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        img_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        img_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        img_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_full_n : IN STD_LOGIC;
        img_data_stream_0_V_write : OUT STD_LOGIC;
        img_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_full_n : IN STD_LOGIC;
        img_data_stream_1_V_write : OUT STD_LOGIC );
    end component;


    component image_filter_sobel_filter_core IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src_data_stream_0_V_empty_n : IN STD_LOGIC;
        src_data_stream_0_V_read : OUT STD_LOGIC;
        src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src_data_stream_1_V_empty_n : IN STD_LOGIC;
        src_data_stream_1_V_read : OUT STD_LOGIC;
        dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst_data_stream_0_V_full_n : IN STD_LOGIC;
        dst_data_stream_0_V_write : OUT STD_LOGIC;
        dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst_data_stream_1_V_full_n : IN STD_LOGIC;
        dst_data_stream_1_V_write : OUT STD_LOGIC;
        rows : IN STD_LOGIC_VECTOR (10 downto 0);
        cols : IN STD_LOGIC_VECTOR (10 downto 0);
        C_XR0C0 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_XR0C1 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_XR0C2 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_XR1C0 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_XR1C1 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_XR1C2 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_XR2C0 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_XR2C1 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_XR2C2 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_YR0C0 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_YR0C1 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_YR0C2 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_YR1C0 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_YR1C1 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_YR1C2 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_YR2C0 : IN STD_LOGIC_VECTOR (31 downto 0);
        C_YR2C1 : IN STD_LOGIC_VECTOR (31 downto 0);
        c_high_thresh : IN STD_LOGIC_VECTOR (31 downto 0);
        c_low_thresh : IN STD_LOGIC_VECTOR (31 downto 0);
        c_invert : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component image_filter_Mat2AXIvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        img_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        img_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_data_stream_0_V_read : OUT STD_LOGIC;
        img_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_data_stream_1_V_read : OUT STD_LOGIC;
        video_out_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        video_out_TVALID : OUT STD_LOGIC;
        video_out_TREADY : IN STD_LOGIC;
        video_out_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
        video_out_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        video_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        video_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component FIFO_image_filter_img_0_rows_V_channel IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_image_filter_img_0_cols_V_channel IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_image_filter_img_1_rows_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_image_filter_img_1_cols_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_image_filter_img_0_data_stream_0_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_image_filter_img_0_data_stream_1_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_image_filter_img_1_data_stream_0_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_image_filter_img_1_data_stream_1_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component image_filter_CONTROL_BUS_s_axi IS
    generic (
        C_ADDR_WIDTH : INTEGER;
        C_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        C_XR0C0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_XR0C1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_XR0C2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_XR1C0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_XR1C1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_XR1C2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_XR2C0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_XR2C1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_XR2C2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_YR0C0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_YR0C1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_YR0C2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_YR1C0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_YR1C1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_YR1C2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_YR2C0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_YR2C1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        C_YR2C2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_high_thresh : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_low_thresh : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_invert : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    image_filter_CONTROL_BUS_s_axi_U : component image_filter_CONTROL_BUS_s_axi
    generic map (
        C_ADDR_WIDTH => C_S_AXI_CONTROL_BUS_ADDR_WIDTH,
        C_DATA_WIDTH => C_S_AXI_CONTROL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CONTROL_BUS_AWVALID,
        AWREADY => s_axi_CONTROL_BUS_AWREADY,
        AWADDR => s_axi_CONTROL_BUS_AWADDR,
        WVALID => s_axi_CONTROL_BUS_WVALID,
        WREADY => s_axi_CONTROL_BUS_WREADY,
        WDATA => s_axi_CONTROL_BUS_WDATA,
        WSTRB => s_axi_CONTROL_BUS_WSTRB,
        ARVALID => s_axi_CONTROL_BUS_ARVALID,
        ARREADY => s_axi_CONTROL_BUS_ARREADY,
        ARADDR => s_axi_CONTROL_BUS_ARADDR,
        RVALID => s_axi_CONTROL_BUS_RVALID,
        RREADY => s_axi_CONTROL_BUS_RREADY,
        RDATA => s_axi_CONTROL_BUS_RDATA,
        RRESP => s_axi_CONTROL_BUS_RRESP,
        BVALID => s_axi_CONTROL_BUS_BVALID,
        BREADY => s_axi_CONTROL_BUS_BREADY,
        BRESP => s_axi_CONTROL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => image_filter_CONTROL_BUS_s_axi_U_ap_dummy_ce,
        rows => rows,
        cols => cols,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        C_XR0C0 => C_XR0C0,
        C_XR0C1 => C_XR0C1,
        C_XR0C2 => C_XR0C2,
        C_XR1C0 => C_XR1C0,
        C_XR1C1 => C_XR1C1,
        C_XR1C2 => C_XR1C2,
        C_XR2C0 => C_XR2C0,
        C_XR2C1 => C_XR2C1,
        C_XR2C2 => C_XR2C2,
        C_YR0C0 => C_YR0C0,
        C_YR0C1 => C_YR0C1,
        C_YR0C2 => C_YR0C2,
        C_YR1C0 => C_YR1C0,
        C_YR1C1 => C_YR1C1,
        C_YR1C2 => C_YR1C2,
        C_YR2C0 => C_YR2C0,
        C_YR2C1 => C_YR2C1,
        C_YR2C2 => C_YR2C2,
        c_high_thresh => c_high_thresh,
        c_low_thresh => c_low_thresh,
        c_invert => c_invert);

    image_filter_Block_proc_U0 : component image_filter_Block_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => image_filter_Block_proc_U0_ap_start,
        ap_done => image_filter_Block_proc_U0_ap_done,
        ap_continue => image_filter_Block_proc_U0_ap_continue,
        ap_idle => image_filter_Block_proc_U0_ap_idle,
        ap_ready => image_filter_Block_proc_U0_ap_ready,
        rows => image_filter_Block_proc_U0_rows,
        cols => image_filter_Block_proc_U0_cols,
        ap_return_0 => image_filter_Block_proc_U0_ap_return_0,
        ap_return_1 => image_filter_Block_proc_U0_ap_return_1,
        ap_return_2 => image_filter_Block_proc_U0_ap_return_2,
        ap_return_3 => image_filter_Block_proc_U0_ap_return_3);

    image_filter_AXIvideo2Mat_U0 : component image_filter_AXIvideo2Mat
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => image_filter_AXIvideo2Mat_U0_ap_start,
        ap_done => image_filter_AXIvideo2Mat_U0_ap_done,
        ap_continue => image_filter_AXIvideo2Mat_U0_ap_continue,
        ap_idle => image_filter_AXIvideo2Mat_U0_ap_idle,
        ap_ready => image_filter_AXIvideo2Mat_U0_ap_ready,
        video_in_TDATA => image_filter_AXIvideo2Mat_U0_video_in_TDATA,
        video_in_TVALID => image_filter_AXIvideo2Mat_U0_video_in_TVALID,
        video_in_TREADY => image_filter_AXIvideo2Mat_U0_video_in_TREADY,
        video_in_TKEEP => image_filter_AXIvideo2Mat_U0_video_in_TKEEP,
        video_in_TSTRB => image_filter_AXIvideo2Mat_U0_video_in_TSTRB,
        video_in_TUSER => image_filter_AXIvideo2Mat_U0_video_in_TUSER,
        video_in_TLAST => image_filter_AXIvideo2Mat_U0_video_in_TLAST,
        video_in_TID => image_filter_AXIvideo2Mat_U0_video_in_TID,
        video_in_TDEST => image_filter_AXIvideo2Mat_U0_video_in_TDEST,
        img_rows_V_read => image_filter_AXIvideo2Mat_U0_img_rows_V_read,
        img_cols_V_read => image_filter_AXIvideo2Mat_U0_img_cols_V_read,
        img_data_stream_0_V_din => image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din,
        img_data_stream_0_V_full_n => image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n,
        img_data_stream_0_V_write => image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write,
        img_data_stream_1_V_din => image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din,
        img_data_stream_1_V_full_n => image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n,
        img_data_stream_1_V_write => image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write);

    image_filter_sobel_filter_core_U0 : component image_filter_sobel_filter_core
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => image_filter_sobel_filter_core_U0_ap_start,
        ap_done => image_filter_sobel_filter_core_U0_ap_done,
        ap_continue => image_filter_sobel_filter_core_U0_ap_continue,
        ap_idle => image_filter_sobel_filter_core_U0_ap_idle,
        ap_ready => image_filter_sobel_filter_core_U0_ap_ready,
        src_data_stream_0_V_dout => image_filter_sobel_filter_core_U0_src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n => image_filter_sobel_filter_core_U0_src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read => image_filter_sobel_filter_core_U0_src_data_stream_0_V_read,
        src_data_stream_1_V_dout => image_filter_sobel_filter_core_U0_src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n => image_filter_sobel_filter_core_U0_src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read => image_filter_sobel_filter_core_U0_src_data_stream_1_V_read,
        dst_data_stream_0_V_din => image_filter_sobel_filter_core_U0_dst_data_stream_0_V_din,
        dst_data_stream_0_V_full_n => image_filter_sobel_filter_core_U0_dst_data_stream_0_V_full_n,
        dst_data_stream_0_V_write => image_filter_sobel_filter_core_U0_dst_data_stream_0_V_write,
        dst_data_stream_1_V_din => image_filter_sobel_filter_core_U0_dst_data_stream_1_V_din,
        dst_data_stream_1_V_full_n => image_filter_sobel_filter_core_U0_dst_data_stream_1_V_full_n,
        dst_data_stream_1_V_write => image_filter_sobel_filter_core_U0_dst_data_stream_1_V_write,
        rows => image_filter_sobel_filter_core_U0_rows,
        cols => image_filter_sobel_filter_core_U0_cols,
        C_XR0C0 => image_filter_sobel_filter_core_U0_C_XR0C0,
        C_XR0C1 => image_filter_sobel_filter_core_U0_C_XR0C1,
        C_XR0C2 => image_filter_sobel_filter_core_U0_C_XR0C2,
        C_XR1C0 => image_filter_sobel_filter_core_U0_C_XR1C0,
        C_XR1C1 => image_filter_sobel_filter_core_U0_C_XR1C1,
        C_XR1C2 => image_filter_sobel_filter_core_U0_C_XR1C2,
        C_XR2C0 => image_filter_sobel_filter_core_U0_C_XR2C0,
        C_XR2C1 => image_filter_sobel_filter_core_U0_C_XR2C1,
        C_XR2C2 => image_filter_sobel_filter_core_U0_C_XR2C2,
        C_YR0C0 => image_filter_sobel_filter_core_U0_C_YR0C0,
        C_YR0C1 => image_filter_sobel_filter_core_U0_C_YR0C1,
        C_YR0C2 => image_filter_sobel_filter_core_U0_C_YR0C2,
        C_YR1C0 => image_filter_sobel_filter_core_U0_C_YR1C0,
        C_YR1C1 => image_filter_sobel_filter_core_U0_C_YR1C1,
        C_YR1C2 => image_filter_sobel_filter_core_U0_C_YR1C2,
        C_YR2C0 => image_filter_sobel_filter_core_U0_C_YR2C0,
        C_YR2C1 => image_filter_sobel_filter_core_U0_C_YR2C1,
        c_high_thresh => image_filter_sobel_filter_core_U0_c_high_thresh,
        c_low_thresh => image_filter_sobel_filter_core_U0_c_low_thresh,
        c_invert => image_filter_sobel_filter_core_U0_c_invert);

    image_filter_Mat2AXIvideo_U0 : component image_filter_Mat2AXIvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => image_filter_Mat2AXIvideo_U0_ap_start,
        ap_done => image_filter_Mat2AXIvideo_U0_ap_done,
        ap_continue => image_filter_Mat2AXIvideo_U0_ap_continue,
        ap_idle => image_filter_Mat2AXIvideo_U0_ap_idle,
        ap_ready => image_filter_Mat2AXIvideo_U0_ap_ready,
        img_rows_V_read => image_filter_Mat2AXIvideo_U0_img_rows_V_read,
        img_cols_V_read => image_filter_Mat2AXIvideo_U0_img_cols_V_read,
        img_data_stream_0_V_dout => image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_dout,
        img_data_stream_0_V_empty_n => image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n,
        img_data_stream_0_V_read => image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_read,
        img_data_stream_1_V_dout => image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_dout,
        img_data_stream_1_V_empty_n => image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n,
        img_data_stream_1_V_read => image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_read,
        video_out_TDATA => image_filter_Mat2AXIvideo_U0_video_out_TDATA,
        video_out_TVALID => image_filter_Mat2AXIvideo_U0_video_out_TVALID,
        video_out_TREADY => image_filter_Mat2AXIvideo_U0_video_out_TREADY,
        video_out_TKEEP => image_filter_Mat2AXIvideo_U0_video_out_TKEEP,
        video_out_TSTRB => image_filter_Mat2AXIvideo_U0_video_out_TSTRB,
        video_out_TUSER => image_filter_Mat2AXIvideo_U0_video_out_TUSER,
        video_out_TLAST => image_filter_Mat2AXIvideo_U0_video_out_TLAST,
        video_out_TID => image_filter_Mat2AXIvideo_U0_video_out_TID,
        video_out_TDEST => image_filter_Mat2AXIvideo_U0_video_out_TDEST);

    img_0_rows_V_channel_U : component FIFO_image_filter_img_0_rows_V_channel
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_rows_V_channel_U_ap_dummy_ce,
        if_write_ce => img_0_rows_V_channel_U_ap_dummy_ce,
        if_din => img_0_rows_V_channel_din,
        if_full_n => img_0_rows_V_channel_full_n,
        if_write => img_0_rows_V_channel_write,
        if_dout => img_0_rows_V_channel_dout,
        if_empty_n => img_0_rows_V_channel_empty_n,
        if_read => img_0_rows_V_channel_read);

    img_0_cols_V_channel_U : component FIFO_image_filter_img_0_cols_V_channel
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_cols_V_channel_U_ap_dummy_ce,
        if_write_ce => img_0_cols_V_channel_U_ap_dummy_ce,
        if_din => img_0_cols_V_channel_din,
        if_full_n => img_0_cols_V_channel_full_n,
        if_write => img_0_cols_V_channel_write,
        if_dout => img_0_cols_V_channel_dout,
        if_empty_n => img_0_cols_V_channel_empty_n,
        if_read => img_0_cols_V_channel_read);

    img_1_rows_V_U : component FIFO_image_filter_img_1_rows_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_1_rows_V_U_ap_dummy_ce,
        if_write_ce => img_1_rows_V_U_ap_dummy_ce,
        if_din => img_1_rows_V_din,
        if_full_n => img_1_rows_V_full_n,
        if_write => img_1_rows_V_write,
        if_dout => img_1_rows_V_dout,
        if_empty_n => img_1_rows_V_empty_n,
        if_read => img_1_rows_V_read);

    img_1_cols_V_U : component FIFO_image_filter_img_1_cols_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_1_cols_V_U_ap_dummy_ce,
        if_write_ce => img_1_cols_V_U_ap_dummy_ce,
        if_din => img_1_cols_V_din,
        if_full_n => img_1_cols_V_full_n,
        if_write => img_1_cols_V_write,
        if_dout => img_1_cols_V_dout,
        if_empty_n => img_1_cols_V_empty_n,
        if_read => img_1_cols_V_read);

    img_0_data_stream_0_V_U : component FIFO_image_filter_img_0_data_stream_0_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_data_stream_0_V_U_ap_dummy_ce,
        if_write_ce => img_0_data_stream_0_V_U_ap_dummy_ce,
        if_din => img_0_data_stream_0_V_din,
        if_full_n => img_0_data_stream_0_V_full_n,
        if_write => img_0_data_stream_0_V_write,
        if_dout => img_0_data_stream_0_V_dout,
        if_empty_n => img_0_data_stream_0_V_empty_n,
        if_read => img_0_data_stream_0_V_read);

    img_0_data_stream_1_V_U : component FIFO_image_filter_img_0_data_stream_1_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_data_stream_1_V_U_ap_dummy_ce,
        if_write_ce => img_0_data_stream_1_V_U_ap_dummy_ce,
        if_din => img_0_data_stream_1_V_din,
        if_full_n => img_0_data_stream_1_V_full_n,
        if_write => img_0_data_stream_1_V_write,
        if_dout => img_0_data_stream_1_V_dout,
        if_empty_n => img_0_data_stream_1_V_empty_n,
        if_read => img_0_data_stream_1_V_read);

    img_1_data_stream_0_V_U : component FIFO_image_filter_img_1_data_stream_0_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_1_data_stream_0_V_U_ap_dummy_ce,
        if_write_ce => img_1_data_stream_0_V_U_ap_dummy_ce,
        if_din => img_1_data_stream_0_V_din,
        if_full_n => img_1_data_stream_0_V_full_n,
        if_write => img_1_data_stream_0_V_write,
        if_dout => img_1_data_stream_0_V_dout,
        if_empty_n => img_1_data_stream_0_V_empty_n,
        if_read => img_1_data_stream_0_V_read);

    img_1_data_stream_1_V_U : component FIFO_image_filter_img_1_data_stream_1_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_1_data_stream_1_V_U_ap_dummy_ce,
        if_write_ce => img_1_data_stream_1_V_U_ap_dummy_ce,
        if_din => img_1_data_stream_1_V_din,
        if_full_n => img_1_data_stream_1_V_full_n,
        if_write => img_1_data_stream_1_V_write,
        if_dout => img_1_data_stream_1_V_dout,
        if_empty_n => img_1_data_stream_1_V_empty_n,
        if_read => img_1_data_stream_1_V_read);





    -- ap_reg_procdone_image_filter_AXIvideo2Mat_U0 assign process. --
    ap_reg_procdone_image_filter_AXIvideo2Mat_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_image_filter_AXIvideo2Mat_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_image_filter_AXIvideo2Mat_U0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = image_filter_AXIvideo2Mat_U0_ap_done)) then 
                    ap_reg_procdone_image_filter_AXIvideo2Mat_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_procdone_image_filter_Block_proc_U0 assign process. --
    ap_reg_procdone_image_filter_Block_proc_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_image_filter_Block_proc_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_image_filter_Block_proc_U0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = image_filter_Block_proc_U0_ap_done)) then 
                    ap_reg_procdone_image_filter_Block_proc_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_procdone_image_filter_Mat2AXIvideo_U0 assign process. --
    ap_reg_procdone_image_filter_Mat2AXIvideo_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_image_filter_Mat2AXIvideo_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_image_filter_Mat2AXIvideo_U0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = image_filter_Mat2AXIvideo_U0_ap_done)) then 
                    ap_reg_procdone_image_filter_Mat2AXIvideo_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_procdone_image_filter_sobel_filter_core_U0 assign process. --
    ap_reg_procdone_image_filter_sobel_filter_core_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_image_filter_sobel_filter_core_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_image_filter_sobel_filter_core_U0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = image_filter_sobel_filter_core_U0_ap_done)) then 
                    ap_reg_procdone_image_filter_sobel_filter_core_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready assign process. --
    ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_start) and (ap_const_logic_1 = ap_sig_top_allready))) then 
                    ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = image_filter_AXIvideo2Mat_U0_ap_ready)) then 
                    ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_image_filter_Block_proc_U0_ap_ready assign process. --
    ap_reg_ready_image_filter_Block_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_image_filter_Block_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_start) and (ap_const_logic_1 = ap_sig_top_allready))) then 
                    ap_reg_ready_image_filter_Block_proc_U0_ap_ready <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = image_filter_Block_proc_U0_ap_ready)) then 
                    ap_reg_ready_image_filter_Block_proc_U0_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready assign process. --
    ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_start) and (ap_const_logic_1 = ap_sig_top_allready))) then 
                    ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = image_filter_sobel_filter_core_U0_ap_ready)) then 
                    ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_img_0_cols_V_channel_full_n assign process. --
    ap_reg_ready_img_0_cols_V_channel_full_n_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_img_0_cols_V_channel_full_n <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = image_filter_Block_proc_U0_ap_done) and (ap_const_logic_1 = image_filter_Block_proc_U0_ap_continue))) then 
                    ap_reg_ready_img_0_cols_V_channel_full_n <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = image_filter_Block_proc_U0_ap_done) and (ap_const_logic_1 = img_0_cols_V_channel_full_n))) then 
                    ap_reg_ready_img_0_cols_V_channel_full_n <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_img_0_rows_V_channel_full_n assign process. --
    ap_reg_ready_img_0_rows_V_channel_full_n_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_img_0_rows_V_channel_full_n <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = image_filter_Block_proc_U0_ap_done) and (ap_const_logic_1 = image_filter_Block_proc_U0_ap_continue))) then 
                    ap_reg_ready_img_0_rows_V_channel_full_n <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = image_filter_Block_proc_U0_ap_done) and (ap_const_logic_1 = img_0_rows_V_channel_full_n))) then 
                    ap_reg_ready_img_0_rows_V_channel_full_n <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_img_1_cols_V_full_n assign process. --
    ap_reg_ready_img_1_cols_V_full_n_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_img_1_cols_V_full_n <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = image_filter_Block_proc_U0_ap_done) and (ap_const_logic_1 = image_filter_Block_proc_U0_ap_continue))) then 
                    ap_reg_ready_img_1_cols_V_full_n <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = image_filter_Block_proc_U0_ap_done) and (ap_const_logic_1 = img_1_cols_V_full_n))) then 
                    ap_reg_ready_img_1_cols_V_full_n <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_img_1_rows_V_full_n assign process. --
    ap_reg_ready_img_1_rows_V_full_n_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_img_1_rows_V_full_n <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = image_filter_Block_proc_U0_ap_done) and (ap_const_logic_1 = image_filter_Block_proc_U0_ap_continue))) then 
                    ap_reg_ready_img_1_rows_V_full_n <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = image_filter_Block_proc_U0_ap_done) and (ap_const_logic_1 = img_1_rows_V_full_n))) then 
                    ap_reg_ready_img_1_rows_V_full_n <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_CS assign process. --
    ap_CS_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_CS <= ap_const_logic_0;
        end if;
    end process;

    -- ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel assign process. --
    ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel_assign_proc : process(image_filter_Block_proc_U0_ap_done, ap_reg_ready_img_0_cols_V_channel_full_n)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_img_0_cols_V_channel_full_n)) then 
            ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel <= ap_const_logic_0;
        else 
            ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel <= image_filter_Block_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel assign process. --
    ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel_assign_proc : process(image_filter_Block_proc_U0_ap_done, ap_reg_ready_img_0_rows_V_channel_full_n)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_img_0_rows_V_channel_full_n)) then 
            ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel <= ap_const_logic_0;
        else 
            ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel <= image_filter_Block_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V assign process. --
    ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V_assign_proc : process(image_filter_Block_proc_U0_ap_done, ap_reg_ready_img_1_cols_V_full_n)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_img_1_cols_V_full_n)) then 
            ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V <= ap_const_logic_0;
        else 
            ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V <= image_filter_Block_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V assign process. --
    ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V_assign_proc : process(image_filter_Block_proc_U0_ap_done, ap_reg_ready_img_1_rows_V_full_n)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_img_1_rows_V_full_n)) then 
            ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V <= ap_const_logic_0;
        else 
            ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V <= image_filter_Block_proc_U0_ap_done;
        end if; 
    end process;

    ap_done <= ap_sig_hs_done;

    -- ap_idle assign process. --
    ap_idle_assign_proc : process(image_filter_Block_proc_U0_ap_idle, image_filter_AXIvideo2Mat_U0_ap_idle, image_filter_sobel_filter_core_U0_ap_idle, image_filter_Mat2AXIvideo_U0_ap_idle, img_0_rows_V_channel_empty_n, img_0_cols_V_channel_empty_n, img_1_rows_V_empty_n, img_1_cols_V_empty_n)
    begin
        if (((ap_const_logic_1 = image_filter_Block_proc_U0_ap_idle) and (ap_const_logic_1 = image_filter_AXIvideo2Mat_U0_ap_idle) and (ap_const_logic_1 = image_filter_sobel_filter_core_U0_ap_idle) and (ap_const_logic_1 = image_filter_Mat2AXIvideo_U0_ap_idle) and (ap_const_logic_0 = img_0_rows_V_channel_empty_n) and (ap_const_logic_0 = img_0_cols_V_channel_empty_n) and (ap_const_logic_0 = img_1_rows_V_empty_n) and (ap_const_logic_0 = img_1_cols_V_empty_n))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_sig_top_allready;

    -- ap_rst_n_inv assign process. --
    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sig_hs_continue <= ap_const_logic_1;

    -- ap_sig_hs_done assign process. --
    ap_sig_hs_done_assign_proc : process(image_filter_Mat2AXIvideo_U0_ap_done)
    begin
        if ((ap_const_logic_1 = image_filter_Mat2AXIvideo_U0_ap_done)) then 
            ap_sig_hs_done <= ap_const_logic_1;
        else 
            ap_sig_hs_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready assign process. --
    ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready_assign_proc : process(image_filter_AXIvideo2Mat_U0_ap_ready, ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready)) then 
            ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready <= image_filter_AXIvideo2Mat_U0_ap_ready;
        else 
            ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_image_filter_Block_proc_U0_ap_ready assign process. --
    ap_sig_ready_image_filter_Block_proc_U0_ap_ready_assign_proc : process(image_filter_Block_proc_U0_ap_ready, ap_reg_ready_image_filter_Block_proc_U0_ap_ready)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_image_filter_Block_proc_U0_ap_ready)) then 
            ap_sig_ready_image_filter_Block_proc_U0_ap_ready <= image_filter_Block_proc_U0_ap_ready;
        else 
            ap_sig_ready_image_filter_Block_proc_U0_ap_ready <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready assign process. --
    ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready_assign_proc : process(image_filter_sobel_filter_core_U0_ap_ready, ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready)) then 
            ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready <= image_filter_sobel_filter_core_U0_ap_ready;
        else 
            ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_img_0_cols_V_channel_full_n assign process. --
    ap_sig_ready_img_0_cols_V_channel_full_n_assign_proc : process(img_0_cols_V_channel_full_n, ap_reg_ready_img_0_cols_V_channel_full_n)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_img_0_cols_V_channel_full_n)) then 
            ap_sig_ready_img_0_cols_V_channel_full_n <= img_0_cols_V_channel_full_n;
        else 
            ap_sig_ready_img_0_cols_V_channel_full_n <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_img_0_rows_V_channel_full_n assign process. --
    ap_sig_ready_img_0_rows_V_channel_full_n_assign_proc : process(img_0_rows_V_channel_full_n, ap_reg_ready_img_0_rows_V_channel_full_n)
    begin
        if ((ap_reg_ready_img_0_rows_V_channel_full_n = ap_const_logic_0)) then 
            ap_sig_ready_img_0_rows_V_channel_full_n <= img_0_rows_V_channel_full_n;
        else 
            ap_sig_ready_img_0_rows_V_channel_full_n <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_img_1_cols_V_full_n assign process. --
    ap_sig_ready_img_1_cols_V_full_n_assign_proc : process(img_1_cols_V_full_n, ap_reg_ready_img_1_cols_V_full_n)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_img_1_cols_V_full_n)) then 
            ap_sig_ready_img_1_cols_V_full_n <= img_1_cols_V_full_n;
        else 
            ap_sig_ready_img_1_cols_V_full_n <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_img_1_rows_V_full_n assign process. --
    ap_sig_ready_img_1_rows_V_full_n_assign_proc : process(img_1_rows_V_full_n, ap_reg_ready_img_1_rows_V_full_n)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_img_1_rows_V_full_n)) then 
            ap_sig_ready_img_1_rows_V_full_n <= img_1_rows_V_full_n;
        else 
            ap_sig_ready_img_1_rows_V_full_n <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start assign process. --
    ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start_assign_proc : process(ap_start, ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready)
    begin
        if (((ap_const_logic_1 = ap_start) and (ap_const_logic_0 = ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready))) then 
            ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start <= ap_const_logic_1;
        else 
            ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_start_in_image_filter_Block_proc_U0_ap_start assign process. --
    ap_sig_start_in_image_filter_Block_proc_U0_ap_start_assign_proc : process(ap_start, ap_reg_ready_image_filter_Block_proc_U0_ap_ready)
    begin
        if (((ap_const_logic_0 = ap_reg_ready_image_filter_Block_proc_U0_ap_ready) and (ap_const_logic_1 = ap_start))) then 
            ap_sig_start_in_image_filter_Block_proc_U0_ap_start <= ap_const_logic_1;
        else 
            ap_sig_start_in_image_filter_Block_proc_U0_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start assign process. --
    ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start_assign_proc : process(ap_start, ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready)
    begin
        if (((ap_const_logic_1 = ap_start) and (ap_const_logic_0 = ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready))) then 
            ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start <= ap_const_logic_1;
        else 
            ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_top_allready assign process. --
    ap_sig_top_allready_assign_proc : process(ap_sig_ready_image_filter_Block_proc_U0_ap_ready, ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready, ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready)
    begin
        if (((ap_const_logic_1 = ap_sig_ready_image_filter_Block_proc_U0_ap_ready) and (ap_const_logic_1 = ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready) and (ap_const_logic_1 = ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready))) then 
            ap_sig_top_allready <= ap_const_logic_1;
        else 
            ap_sig_top_allready <= ap_const_logic_0;
        end if; 
    end process;

    image_filter_AXIvideo2Mat_U0_ap_continue <= ap_const_logic_1;
    image_filter_AXIvideo2Mat_U0_ap_start <= (img_0_rows_V_channel_empty_n and img_0_cols_V_channel_empty_n and ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start);
    image_filter_AXIvideo2Mat_U0_img_cols_V_read <= img_0_cols_V_channel_dout;
    image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n <= img_0_data_stream_0_V_full_n;
    image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n <= img_0_data_stream_1_V_full_n;
    image_filter_AXIvideo2Mat_U0_img_rows_V_read <= img_0_rows_V_channel_dout;
    image_filter_AXIvideo2Mat_U0_video_in_TDATA <= video_in_TDATA;
    image_filter_AXIvideo2Mat_U0_video_in_TDEST <= video_in_TDEST;
    image_filter_AXIvideo2Mat_U0_video_in_TID <= video_in_TID;
    image_filter_AXIvideo2Mat_U0_video_in_TKEEP <= video_in_TKEEP;
    image_filter_AXIvideo2Mat_U0_video_in_TLAST <= video_in_TLAST;
    image_filter_AXIvideo2Mat_U0_video_in_TSTRB <= video_in_TSTRB;
    image_filter_AXIvideo2Mat_U0_video_in_TUSER <= video_in_TUSER;
    image_filter_AXIvideo2Mat_U0_video_in_TVALID <= video_in_TVALID;

    -- image_filter_Block_proc_U0_ap_continue assign process. --
    image_filter_Block_proc_U0_ap_continue_assign_proc : process(ap_sig_ready_img_0_rows_V_channel_full_n, ap_sig_ready_img_0_cols_V_channel_full_n, ap_sig_ready_img_1_rows_V_full_n, ap_sig_ready_img_1_cols_V_full_n)
    begin
        if (((ap_const_logic_1 = ap_sig_ready_img_0_rows_V_channel_full_n) and (ap_const_logic_1 = ap_sig_ready_img_0_cols_V_channel_full_n) and (ap_const_logic_1 = ap_sig_ready_img_1_rows_V_full_n) and (ap_const_logic_1 = ap_sig_ready_img_1_cols_V_full_n))) then 
            image_filter_Block_proc_U0_ap_continue <= ap_const_logic_1;
        else 
            image_filter_Block_proc_U0_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    image_filter_Block_proc_U0_ap_start <= ap_sig_start_in_image_filter_Block_proc_U0_ap_start;
    image_filter_Block_proc_U0_cols <= cols;
    image_filter_Block_proc_U0_rows <= rows;
    image_filter_CONTROL_BUS_s_axi_U_ap_dummy_ce <= ap_const_logic_1;
    image_filter_Mat2AXIvideo_U0_ap_continue <= ap_sig_hs_continue;
    image_filter_Mat2AXIvideo_U0_ap_start <= (img_1_rows_V_empty_n and img_1_cols_V_empty_n);
    image_filter_Mat2AXIvideo_U0_img_cols_V_read <= img_1_cols_V_dout;
    image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_dout <= img_1_data_stream_0_V_dout;
    image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n <= img_1_data_stream_0_V_empty_n;
    image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_dout <= img_1_data_stream_1_V_dout;
    image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n <= img_1_data_stream_1_V_empty_n;
    image_filter_Mat2AXIvideo_U0_img_rows_V_read <= img_1_rows_V_dout;
    image_filter_Mat2AXIvideo_U0_video_out_TREADY <= video_out_TREADY;
    image_filter_sobel_filter_core_U0_C_XR0C0 <= C_XR0C0;
    image_filter_sobel_filter_core_U0_C_XR0C1 <= C_XR0C1;
    image_filter_sobel_filter_core_U0_C_XR0C2 <= C_XR0C2;
    image_filter_sobel_filter_core_U0_C_XR1C0 <= C_XR1C0;
    image_filter_sobel_filter_core_U0_C_XR1C1 <= C_XR1C1;
    image_filter_sobel_filter_core_U0_C_XR1C2 <= C_XR1C2;
    image_filter_sobel_filter_core_U0_C_XR2C0 <= C_XR2C0;
    image_filter_sobel_filter_core_U0_C_XR2C1 <= C_XR2C1;
    image_filter_sobel_filter_core_U0_C_XR2C2 <= C_XR2C2;
    image_filter_sobel_filter_core_U0_C_YR0C0 <= C_YR0C0;
    image_filter_sobel_filter_core_U0_C_YR0C1 <= C_YR0C1;
    image_filter_sobel_filter_core_U0_C_YR0C2 <= C_YR0C2;
    image_filter_sobel_filter_core_U0_C_YR1C0 <= C_YR1C0;
    image_filter_sobel_filter_core_U0_C_YR1C1 <= C_YR1C1;
    image_filter_sobel_filter_core_U0_C_YR1C2 <= C_YR1C2;
    image_filter_sobel_filter_core_U0_C_YR2C0 <= C_YR2C0;
    image_filter_sobel_filter_core_U0_C_YR2C1 <= C_YR2C1;
    image_filter_sobel_filter_core_U0_ap_continue <= ap_const_logic_1;
    image_filter_sobel_filter_core_U0_ap_start <= ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start;
    image_filter_sobel_filter_core_U0_c_high_thresh <= c_high_thresh;
    image_filter_sobel_filter_core_U0_c_invert <= c_invert;
    image_filter_sobel_filter_core_U0_c_low_thresh <= c_low_thresh;
    
    image_filter_sobel_filter_core_U0_cols_proc : process(cols)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable image_filter_sobel_filter_core_U0_cols_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_B(5 - 1 downto 0);
        v0_cpy := cols;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_B(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for image_filter_sobel_filter_core_U0_cols_i in 0 to 32-1 loop
                v0_cpy(image_filter_sobel_filter_core_U0_cols_i) := cols(32-1-image_filter_sobel_filter_core_U0_cols_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy),to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        image_filter_sobel_filter_core_U0_cols <= resvalue(11-1 downto 0);
    end process;

    image_filter_sobel_filter_core_U0_dst_data_stream_0_V_full_n <= img_1_data_stream_0_V_full_n;
    image_filter_sobel_filter_core_U0_dst_data_stream_1_V_full_n <= img_1_data_stream_1_V_full_n;
    
    image_filter_sobel_filter_core_U0_rows_proc : process(rows)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable image_filter_sobel_filter_core_U0_rows_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_B(5 - 1 downto 0);
        v0_cpy := rows;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_B(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for image_filter_sobel_filter_core_U0_rows_i in 0 to 32-1 loop
                v0_cpy(image_filter_sobel_filter_core_U0_rows_i) := rows(32-1-image_filter_sobel_filter_core_U0_rows_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy),to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        image_filter_sobel_filter_core_U0_rows <= resvalue(11-1 downto 0);
    end process;

    image_filter_sobel_filter_core_U0_src_data_stream_0_V_dout <= img_0_data_stream_0_V_dout;
    image_filter_sobel_filter_core_U0_src_data_stream_0_V_empty_n <= img_0_data_stream_0_V_empty_n;
    image_filter_sobel_filter_core_U0_src_data_stream_1_V_dout <= img_0_data_stream_1_V_dout;
    image_filter_sobel_filter_core_U0_src_data_stream_1_V_empty_n <= img_0_data_stream_1_V_empty_n;
    img_0_cols_V_channel_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_cols_V_channel_din <= image_filter_Block_proc_U0_ap_return_1;
    img_0_cols_V_channel_read <= image_filter_AXIvideo2Mat_U0_ap_ready;
    img_0_cols_V_channel_write <= ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel;
    img_0_data_stream_0_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_data_stream_0_V_din <= image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din;
    img_0_data_stream_0_V_read <= image_filter_sobel_filter_core_U0_src_data_stream_0_V_read;
    img_0_data_stream_0_V_write <= image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write;
    img_0_data_stream_1_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_data_stream_1_V_din <= image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din;
    img_0_data_stream_1_V_read <= image_filter_sobel_filter_core_U0_src_data_stream_1_V_read;
    img_0_data_stream_1_V_write <= image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write;
    img_0_rows_V_channel_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_rows_V_channel_din <= image_filter_Block_proc_U0_ap_return_0;
    img_0_rows_V_channel_read <= image_filter_AXIvideo2Mat_U0_ap_ready;
    img_0_rows_V_channel_write <= ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel;
    img_1_cols_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_1_cols_V_din <= image_filter_Block_proc_U0_ap_return_3;
    img_1_cols_V_read <= image_filter_Mat2AXIvideo_U0_ap_ready;
    img_1_cols_V_write <= ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V;
    img_1_data_stream_0_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_1_data_stream_0_V_din <= image_filter_sobel_filter_core_U0_dst_data_stream_0_V_din;
    img_1_data_stream_0_V_read <= image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_read;
    img_1_data_stream_0_V_write <= image_filter_sobel_filter_core_U0_dst_data_stream_0_V_write;
    img_1_data_stream_1_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_1_data_stream_1_V_din <= image_filter_sobel_filter_core_U0_dst_data_stream_1_V_din;
    img_1_data_stream_1_V_read <= image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_read;
    img_1_data_stream_1_V_write <= image_filter_sobel_filter_core_U0_dst_data_stream_1_V_write;
    img_1_rows_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_1_rows_V_din <= image_filter_Block_proc_U0_ap_return_2;
    img_1_rows_V_read <= image_filter_Mat2AXIvideo_U0_ap_ready;
    img_1_rows_V_write <= ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V;
    video_in_TREADY <= image_filter_AXIvideo2Mat_U0_video_in_TREADY;
    video_out_TDATA <= image_filter_Mat2AXIvideo_U0_video_out_TDATA;
    video_out_TDEST <= image_filter_Mat2AXIvideo_U0_video_out_TDEST;
    video_out_TID <= image_filter_Mat2AXIvideo_U0_video_out_TID;
    video_out_TKEEP <= image_filter_Mat2AXIvideo_U0_video_out_TKEEP;
    video_out_TLAST <= image_filter_Mat2AXIvideo_U0_video_out_TLAST;
    video_out_TSTRB <= image_filter_Mat2AXIvideo_U0_video_out_TSTRB;
    video_out_TUSER <= image_filter_Mat2AXIvideo_U0_video_out_TUSER;
    video_out_TVALID <= image_filter_Mat2AXIvideo_U0_video_out_TVALID;
end behav;
