// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_sobel_filter_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read,
        dst_data_stream_0_V_din,
        dst_data_stream_0_V_full_n,
        dst_data_stream_0_V_write,
        dst_data_stream_1_V_din,
        dst_data_stream_1_V_full_n,
        dst_data_stream_1_V_write,
        rows,
        cols,
        C_XR0C0,
        C_XR0C1,
        C_XR0C2,
        C_XR1C0,
        C_XR1C1,
        C_XR1C2,
        C_XR2C0,
        C_XR2C1,
        C_XR2C2,
        C_YR0C0,
        C_YR0C1,
        C_YR0C2,
        C_YR1C0,
        C_YR1C1,
        C_YR1C2,
        C_YR2C0,
        C_YR2C1,
        c_high_thresh,
        c_low_thresh,
        c_invert
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_st2_fsm_1 = 3'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv8_80 = 8'b10000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv16_FF = 16'b11111111;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
input  [7:0] src_data_stream_1_V_dout;
input   src_data_stream_1_V_empty_n;
output   src_data_stream_1_V_read;
output  [7:0] dst_data_stream_0_V_din;
input   dst_data_stream_0_V_full_n;
output   dst_data_stream_0_V_write;
output  [7:0] dst_data_stream_1_V_din;
input   dst_data_stream_1_V_full_n;
output   dst_data_stream_1_V_write;
input  [10:0] rows;
input  [10:0] cols;
input  [31:0] C_XR0C0;
input  [31:0] C_XR0C1;
input  [31:0] C_XR0C2;
input  [31:0] C_XR1C0;
input  [31:0] C_XR1C1;
input  [31:0] C_XR1C2;
input  [31:0] C_XR2C0;
input  [31:0] C_XR2C1;
input  [31:0] C_XR2C2;
input  [31:0] C_YR0C0;
input  [31:0] C_YR0C1;
input  [31:0] C_YR0C2;
input  [31:0] C_YR1C0;
input  [31:0] C_YR1C1;
input  [31:0] C_YR1C2;
input  [31:0] C_YR2C0;
input  [31:0] C_YR2C1;
input  [31:0] c_high_thresh;
input  [31:0] c_low_thresh;
input  [31:0] c_invert;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_data_stream_0_V_read;
reg src_data_stream_1_V_read;
reg dst_data_stream_0_V_write;
reg dst_data_stream_1_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm = 3'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
reg   [11:0] col_assign_reg_403;
reg   [11:0] ap_reg_ppstg_col_assign_reg_403_pp0_it1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_75;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg   [0:0] tmp_1_reg_1324;
reg   [0:0] ap_reg_ppstg_tmp_1_reg_1324_pp0_it1;
reg   [0:0] or_cond_reg_1353;
reg   [0:0] ap_reg_ppstg_or_cond_reg_1353_pp0_it1;
reg    ap_sig_bdd_96;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg    ap_reg_ppiten_pp0_it9 = 1'b0;
reg    ap_reg_ppiten_pp0_it10 = 1'b0;
reg    ap_reg_ppiten_pp0_it11 = 1'b0;
reg   [0:0] or_cond3_reg_1357;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it11;
reg    ap_sig_bdd_127;
reg    ap_reg_ppiten_pp0_it12 = 1'b0;
reg    ap_sig_bdd_139;
wire   [11:0] cols_cast2_cast_fu_416_p1;
reg   [11:0] cols_cast2_cast_reg_1175;
wire   [11:0] rows_cast1_cast_fu_420_p1;
reg   [11:0] rows_cast1_cast_reg_1180;
wire   [11:0] tmp_fu_424_p2;
reg   [11:0] tmp_reg_1185;
wire   [11:0] tmp_s_fu_430_p2;
reg   [11:0] tmp_s_reg_1190;
wire  signed [12:0] tmp_5_cast_fu_442_p1;
reg  signed [12:0] tmp_5_cast_reg_1195;
wire  signed [12:0] tmp_6_cast_fu_452_p1;
reg  signed [12:0] tmp_6_cast_reg_1200;
wire  signed [15:0] tmp_36_0_i_fu_524_p1;
reg  signed [15:0] tmp_36_0_i_reg_1205;
wire  signed [15:0] tmp_38_0_i_fu_528_p1;
reg  signed [15:0] tmp_38_0_i_reg_1210;
wire  signed [15:0] tmp_36_0_1_i_fu_532_p1;
reg  signed [15:0] tmp_36_0_1_i_reg_1215;
wire  signed [15:0] tmp_38_0_1_i_fu_536_p1;
reg  signed [15:0] tmp_38_0_1_i_reg_1220;
wire  signed [15:0] tmp_36_0_2_i_fu_540_p1;
reg  signed [15:0] tmp_36_0_2_i_reg_1225;
wire  signed [15:0] tmp_38_0_2_i_fu_544_p1;
reg  signed [15:0] tmp_38_0_2_i_reg_1230;
wire  signed [15:0] tmp_36_1_i_fu_548_p1;
reg  signed [15:0] tmp_36_1_i_reg_1235;
wire  signed [15:0] tmp_38_1_i_fu_552_p1;
reg  signed [15:0] tmp_38_1_i_reg_1240;
wire  signed [15:0] tmp_36_1_1_i_fu_556_p1;
reg  signed [15:0] tmp_36_1_1_i_reg_1245;
wire  signed [15:0] tmp_38_1_1_i_fu_560_p1;
reg  signed [15:0] tmp_38_1_1_i_reg_1250;
wire  signed [15:0] tmp_36_1_2_i_fu_564_p1;
reg  signed [15:0] tmp_36_1_2_i_reg_1255;
wire  signed [15:0] tmp_38_1_2_i_fu_568_p1;
reg  signed [15:0] tmp_38_1_2_i_reg_1260;
wire  signed [15:0] tmp_36_2_i_fu_572_p1;
reg  signed [15:0] tmp_36_2_i_reg_1265;
wire  signed [15:0] tmp_38_2_i_fu_576_p1;
reg  signed [15:0] tmp_38_2_i_reg_1270;
wire  signed [15:0] tmp_36_2_1_i_fu_580_p1;
reg  signed [15:0] tmp_36_2_1_i_reg_1275;
wire  signed [15:0] tmp_38_2_1_i_fu_584_p1;
reg  signed [15:0] tmp_38_2_1_i_reg_1280;
wire  signed [15:0] tmp_36_2_2_i_fu_588_p1;
reg  signed [15:0] tmp_36_2_2_i_reg_1285;
wire   [0:0] tmp_33_i_fu_592_p2;
reg   [0:0] tmp_33_i_reg_1290;
wire   [0:0] tmp_7_fu_602_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_199;
wire   [11:0] row_1_fu_607_p2;
reg   [11:0] row_1_reg_1299;
wire   [0:0] tmp_8_fu_613_p2;
reg   [0:0] tmp_8_reg_1304;
wire   [0:0] icmp_fu_628_p2;
reg   [0:0] icmp_reg_1309;
wire   [0:0] tmp_3_fu_634_p2;
reg   [0:0] tmp_3_reg_1314;
wire   [0:0] tmp_4_fu_640_p2;
reg   [0:0] tmp_4_reg_1319;
wire   [0:0] tmp_1_fu_645_p2;
reg   [0:0] ap_reg_ppstg_tmp_1_reg_1324_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_1_reg_1324_pp0_it3;
wire   [11:0] col_fu_650_p2;
reg   [11:0] col_reg_1328;
wire   [0:0] tmp_11_fu_656_p2;
reg   [0:0] tmp_11_reg_1333;
reg   [0:0] ap_reg_ppstg_tmp_11_reg_1333_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_11_reg_1333_pp0_it2;
wire   [63:0] tmp_12_fu_661_p1;
reg   [63:0] tmp_12_reg_1337;
reg   [10:0] buff_A_val_1_addr_reg_1342;
wire   [0:0] or_cond_fu_667_p2;
wire   [0:0] or_cond3_fu_678_p2;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it6;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it7;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it8;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it9;
reg   [0:0] ap_reg_ppstg_or_cond3_reg_1357_pp0_it10;
reg   [7:0] buff_C_val_1_0_1_load_reg_1361;
wire   [0:0] or_cond4_fu_741_p2;
reg   [0:0] or_cond4_reg_1371;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_1371_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_1371_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_1371_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_1371_pp0_it6;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_1371_pp0_it7;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_1371_pp0_it8;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_1371_pp0_it9;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_1371_pp0_it10;
reg   [0:0] ap_reg_ppstg_or_cond4_reg_1371_pp0_it11;
reg   [7:0] buff_C_val_0_1_reg_1376;
reg   [7:0] ap_reg_ppstg_buff_C_val_0_1_reg_1376_pp0_it4;
reg   [7:0] buff_C_val_1_1_reg_1382;
reg   [7:0] ap_reg_ppstg_buff_C_val_1_1_reg_1382_pp0_it4;
reg   [7:0] buff_C_val_2_1_reg_1388;
reg   [7:0] ap_reg_ppstg_buff_C_val_2_1_reg_1388_pp0_it4;
reg   [7:0] buff_C_val_1_0_load_reg_1398;
wire   [15:0] tmp_35_0_i_fu_805_p1;
wire   [15:0] tmp_35_0_2_i_fu_819_p1;
wire   [15:0] tmp_35_1_2_i_fu_833_p1;
wire   [15:0] tmp_35_2_i_fu_847_p1;
wire   [15:0] tmp_35_0_1_i_fu_869_p1;
wire   [15:0] tmp_35_1_i_fu_882_p1;
wire   [15:0] tmp_35_1_1_i_fu_895_p1;
wire   [15:0] tmp_35_2_1_i_fu_908_p1;
wire  signed [15:0] grp_fu_780_p2;
reg  signed [15:0] tmp_37_2_2_i_reg_1451;
wire  signed [15:0] grp_fu_809_p2;
reg  signed [15:0] tmp_37_0_i_reg_1457;
wire  signed [15:0] grp_fu_814_p2;
reg  signed [15:0] tmp_39_0_i_reg_1462;
wire  signed [15:0] grp_fu_837_p2;
reg  signed [15:0] tmp_37_1_2_i_reg_1467;
wire  signed [15:0] grp_fu_842_p2;
reg  signed [15:0] tmp_39_1_2_i_reg_1472;
wire  signed [15:0] grp_fu_851_p2;
reg  signed [15:0] tmp_37_2_i_reg_1477;
wire  signed [15:0] grp_fu_856_p2;
reg  signed [15:0] tmp_39_2_i_reg_1482;
wire  signed [15:0] tmp7_fu_921_p2;
reg  signed [15:0] tmp7_reg_1487;
wire  signed [15:0] tmp14_fu_926_p2;
reg  signed [15:0] tmp14_reg_1492;
wire  signed [15:0] tmp3_fu_931_p2;
reg  signed [15:0] tmp3_reg_1497;
wire  signed [15:0] tmp4_fu_936_p2;
reg  signed [15:0] tmp4_reg_1502;
wire  signed [15:0] tmp6_fu_941_p2;
reg  signed [15:0] tmp6_reg_1507;
wire  signed [15:0] tmp8_fu_946_p2;
reg  signed [15:0] tmp8_reg_1512;
wire  signed [15:0] tmp10_fu_951_p2;
reg  signed [15:0] tmp10_reg_1517;
wire  signed [15:0] tmp11_fu_956_p2;
reg  signed [15:0] tmp11_reg_1522;
wire  signed [15:0] tmp13_fu_961_p2;
reg  signed [15:0] tmp13_reg_1527;
wire  signed [15:0] tmp15_fu_966_p2;
reg  signed [15:0] tmp15_reg_1532;
wire  signed [15:0] x_weight_2_2_2_i_fu_979_p2;
reg  signed [15:0] x_weight_2_2_2_i_reg_1537;
wire  signed [15:0] y_weight_2_2_2_i_fu_993_p2;
reg  signed [15:0] y_weight_2_2_2_i_reg_1544;
wire   [15:0] edge_weight_fu_1033_p2;
reg   [15:0] edge_weight_reg_1551;
wire   [7:0] tmp_40_fu_1039_p1;
reg   [7:0] tmp_40_reg_1556;
wire   [7:0] edge_val1_i_fu_1053_p3;
reg   [7:0] edge_val1_i_reg_1561;
wire   [7:0] edge_val_2_i_fu_1088_p3;
reg   [7:0] edge_val_2_i_reg_1567;
wire   [10:0] buff_A_val_0_address0;
reg    buff_A_val_0_ce0;
wire   [7:0] buff_A_val_0_q0;
wire   [10:0] buff_A_val_0_address1;
reg    buff_A_val_0_ce1;
reg    buff_A_val_0_we1;
wire   [7:0] buff_A_val_0_d1;
wire   [10:0] buff_A_val_1_address0;
reg    buff_A_val_1_ce0;
wire   [7:0] buff_A_val_1_q0;
wire   [10:0] buff_A_val_1_address1;
reg    buff_A_val_1_ce1;
reg    buff_A_val_1_we1;
wire   [7:0] buff_A_val_1_d1;
wire   [10:0] buff_A_val_2_address0;
reg    buff_A_val_2_ce0;
reg    buff_A_val_2_we0;
wire   [7:0] buff_A_val_2_d0;
wire   [10:0] buff_A_val_2_address1;
reg    buff_A_val_2_ce1;
wire   [7:0] buff_A_val_2_q1;
reg   [11:0] row_reg_392;
reg   [11:0] col_assign_phi_fu_407_p4;
wire   [63:0] tmp_15_fu_692_p1;
wire   [63:0] tmp_17_fu_705_p1;
reg   [7:0] buff_C_val_1_0_1_fu_130;
reg   [7:0] buff_C_val_0_0_s_fu_134;
reg   [7:0] buff_C_val_0_1_s_fu_138;
reg   [7:0] buff_C_val_0_0_1_fu_142;
reg   [7:0] buff_C_val_1_0_s_fu_146;
reg   [7:0] buff_C_val_1_1_s_fu_150;
reg   [7:0] buff_C_val_2_1_s_fu_154;
reg   [7:0] buff_C_val_2_0_s_fu_158;
wire   [11:0] tmp_5_fu_436_p2;
wire   [11:0] tmp_6_fu_446_p2;
wire   [7:0] tmp_2_fu_456_p1;
wire   [7:0] tmp_29_fu_492_p1;
wire   [7:0] tmp_9_fu_460_p1;
wire   [7:0] tmp_30_fu_496_p1;
wire   [7:0] tmp_13_fu_464_p1;
wire   [7:0] tmp_31_fu_500_p1;
wire   [7:0] tmp_16_fu_468_p1;
wire   [7:0] tmp_32_fu_504_p1;
wire   [7:0] tmp_18_fu_472_p1;
wire   [7:0] tmp_33_fu_508_p1;
wire   [7:0] tmp_20_fu_476_p1;
wire   [7:0] tmp_34_fu_512_p1;
wire   [7:0] tmp_26_fu_480_p1;
wire   [7:0] tmp_35_fu_516_p1;
wire   [7:0] tmp_27_fu_484_p1;
wire   [7:0] tmp_36_fu_520_p1;
wire   [7:0] tmp_28_fu_488_p1;
wire   [10:0] tmp_37_fu_618_p4;
wire   [12:0] row_cast_cast_fu_598_p1;
wire   [0:0] tmp_23_fu_672_p2;
wire   [10:0] tmp_39_fu_710_p4;
wire   [12:0] col_assign_cast_cast_fu_688_p1;
wire   [0:0] icmp1_fu_720_p2;
wire   [0:0] tmp_19_fu_726_p2;
wire   [0:0] tmp2_fu_736_p2;
wire   [0:0] tmp1_fu_731_p2;
wire  signed [7:0] grp_fu_780_p0;
wire   [7:0] grp_fu_780_p1;
wire  signed [7:0] grp_fu_809_p0;
wire   [7:0] grp_fu_809_p1;
wire  signed [7:0] grp_fu_814_p0;
wire   [7:0] grp_fu_814_p1;
wire  signed [7:0] grp_fu_823_p0;
wire   [7:0] grp_fu_823_p1;
wire  signed [7:0] grp_fu_828_p0;
wire   [7:0] grp_fu_828_p1;
wire  signed [7:0] grp_fu_837_p0;
wire   [7:0] grp_fu_837_p1;
wire  signed [7:0] grp_fu_842_p0;
wire   [7:0] grp_fu_842_p1;
wire  signed [7:0] grp_fu_851_p0;
wire   [7:0] grp_fu_851_p1;
wire  signed [7:0] grp_fu_856_p0;
wire   [7:0] grp_fu_856_p1;
wire  signed [7:0] grp_fu_872_p0;
wire   [7:0] grp_fu_872_p1;
wire  signed [7:0] grp_fu_877_p0;
wire   [7:0] grp_fu_877_p1;
wire  signed [7:0] grp_fu_885_p0;
wire   [7:0] grp_fu_885_p1;
wire  signed [7:0] grp_fu_890_p0;
wire   [7:0] grp_fu_890_p1;
wire  signed [7:0] grp_fu_898_p0;
wire   [7:0] grp_fu_898_p1;
wire  signed [7:0] grp_fu_903_p0;
wire   [7:0] grp_fu_903_p1;
wire  signed [7:0] grp_fu_911_p0;
wire   [7:0] grp_fu_911_p1;
wire  signed [7:0] grp_fu_916_p0;
wire   [7:0] grp_fu_916_p1;
wire  signed [15:0] grp_fu_823_p2;
wire  signed [15:0] grp_fu_828_p2;
wire  signed [15:0] grp_fu_911_p2;
wire  signed [15:0] grp_fu_898_p2;
wire  signed [15:0] grp_fu_872_p2;
wire  signed [15:0] grp_fu_885_p2;
wire  signed [15:0] grp_fu_916_p2;
wire  signed [15:0] grp_fu_903_p2;
wire  signed [15:0] grp_fu_877_p2;
wire  signed [15:0] grp_fu_890_p2;
(* use_dsp48 = "no" *) wire  signed [15:0] tmp9_fu_975_p2;
(* use_dsp48 = "no" *) wire  signed [15:0] tmp5_fu_971_p2;
(* use_dsp48 = "no" *) wire  signed [15:0] tmp16_fu_989_p2;
(* use_dsp48 = "no" *) wire  signed [15:0] tmp12_fu_985_p2;
wire   [0:0] tmp_17_i_fu_999_p2;
wire  signed [15:0] tmp_18_i_fu_1004_p2;
wire   [0:0] tmp_20_i_fu_1016_p2;
wire  signed [15:0] tmp_21_i_fu_1021_p2;
wire   [15:0] tmp_19_i_fu_1009_p3;
wire   [15:0] tmp_22_i_fu_1026_p3;
wire   [0:0] tmp_23_i_fu_1043_p2;
wire   [7:0] edge_val_fu_1048_p2;
wire   [31:0] tmp_26_i_fu_1061_p1;
wire   [0:0] tmp_27_i_fu_1064_p2;
wire   [0:0] tmp_28_i_fu_1069_p2;
wire   [0:0] tmp_21_fu_1082_p2;
wire   [7:0] p_edge_val_i_fu_1074_p3;
wire   [7:0] edge_val_1_fu_1095_p2;
wire   [7:0] edge_val_3_fu_1100_p3;
reg    grp_fu_780_ce;
reg    grp_fu_809_ce;
reg    grp_fu_814_ce;
reg    grp_fu_823_ce;
reg    grp_fu_828_ce;
reg    grp_fu_837_ce;
reg    grp_fu_842_ce;
reg    grp_fu_851_ce;
reg    grp_fu_856_ce;
reg    grp_fu_872_ce;
reg    grp_fu_877_ce;
reg    grp_fu_885_ce;
reg    grp_fu_890_ce;
reg    grp_fu_898_ce;
reg    grp_fu_903_ce;
reg    grp_fu_911_ce;
reg    grp_fu_916_ce;
reg   [2:0] ap_NS_fsm;
wire   [15:0] grp_fu_780_p10;


image_filter_sobel_filter_core_buff_A_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buff_A_val_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buff_A_val_0_address0 ),
    .ce0( buff_A_val_0_ce0 ),
    .q0( buff_A_val_0_q0 ),
    .address1( buff_A_val_0_address1 ),
    .ce1( buff_A_val_0_ce1 ),
    .we1( buff_A_val_0_we1 ),
    .d1( buff_A_val_0_d1 )
);

image_filter_sobel_filter_core_buff_A_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buff_A_val_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buff_A_val_1_address0 ),
    .ce0( buff_A_val_1_ce0 ),
    .q0( buff_A_val_1_q0 ),
    .address1( buff_A_val_1_address1 ),
    .ce1( buff_A_val_1_ce1 ),
    .we1( buff_A_val_1_we1 ),
    .d1( buff_A_val_1_d1 )
);

image_filter_sobel_filter_core_buff_A_val_2 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buff_A_val_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buff_A_val_2_address0 ),
    .ce0( buff_A_val_2_ce0 ),
    .we0( buff_A_val_2_we0 ),
    .d0( buff_A_val_2_d0 ),
    .address1( buff_A_val_2_address1 ),
    .ce1( buff_A_val_2_ce1 ),
    .q1( buff_A_val_2_q1 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U14(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_780_p0 ),
    .din1( grp_fu_780_p1 ),
    .ce( grp_fu_780_ce ),
    .dout( grp_fu_780_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U15(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_809_p0 ),
    .din1( grp_fu_809_p1 ),
    .ce( grp_fu_809_ce ),
    .dout( grp_fu_809_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U16(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_814_p0 ),
    .din1( grp_fu_814_p1 ),
    .ce( grp_fu_814_ce ),
    .dout( grp_fu_814_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U17(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_823_p0 ),
    .din1( grp_fu_823_p1 ),
    .ce( grp_fu_823_ce ),
    .dout( grp_fu_823_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U18(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_828_p0 ),
    .din1( grp_fu_828_p1 ),
    .ce( grp_fu_828_ce ),
    .dout( grp_fu_828_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U19(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_837_p0 ),
    .din1( grp_fu_837_p1 ),
    .ce( grp_fu_837_ce ),
    .dout( grp_fu_837_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U20(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_842_p0 ),
    .din1( grp_fu_842_p1 ),
    .ce( grp_fu_842_ce ),
    .dout( grp_fu_842_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U21(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_851_p0 ),
    .din1( grp_fu_851_p1 ),
    .ce( grp_fu_851_ce ),
    .dout( grp_fu_851_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U22(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_856_p0 ),
    .din1( grp_fu_856_p1 ),
    .ce( grp_fu_856_ce ),
    .dout( grp_fu_856_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U23(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_872_p0 ),
    .din1( grp_fu_872_p1 ),
    .ce( grp_fu_872_ce ),
    .dout( grp_fu_872_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U24(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_877_p0 ),
    .din1( grp_fu_877_p1 ),
    .ce( grp_fu_877_ce ),
    .dout( grp_fu_877_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U25(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_885_p0 ),
    .din1( grp_fu_885_p1 ),
    .ce( grp_fu_885_ce ),
    .dout( grp_fu_885_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U26(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_890_p0 ),
    .din1( grp_fu_890_p1 ),
    .ce( grp_fu_890_ce ),
    .dout( grp_fu_890_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U27(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_898_p0 ),
    .din1( grp_fu_898_p1 ),
    .ce( grp_fu_898_ce ),
    .dout( grp_fu_898_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U28(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_903_p0 ),
    .din1( grp_fu_903_p1 ),
    .ce( grp_fu_903_ce ),
    .dout( grp_fu_903_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U29(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_911_p0 ),
    .din1( grp_fu_911_p1 ),
    .ce( grp_fu_911_ce ),
    .dout( grp_fu_911_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U30(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_916_p0 ),
    .din1( grp_fu_916_p1 ),
    .ce( grp_fu_916_ce ),
    .dout( grp_fu_916_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == tmp_7_fu_602_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == tmp_1_fu_645_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == tmp_7_fu_602_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == tmp_7_fu_602_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it10 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it10
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it10 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it10 <= ap_reg_ppiten_pp0_it9;
        end
    end
end

/// ap_reg_ppiten_pp0_it11 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it11
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it11 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it11 <= ap_reg_ppiten_pp0_it10;
        end
    end
end

/// ap_reg_ppiten_pp0_it12 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it12
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it12 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it12 <= ap_reg_ppiten_pp0_it11;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == tmp_7_fu_602_p2))) begin
            ap_reg_ppiten_pp0_it12 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
                ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
            end
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

/// ap_reg_ppiten_pp0_it8 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

/// ap_reg_ppiten_pp0_it9 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it9
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(tmp_1_reg_1324 == ap_const_lv1_0))) begin
        col_assign_reg_403 <= col_reg_1328;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == tmp_7_fu_602_p2))) begin
        col_assign_reg_403 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        row_reg_392 <= row_1_reg_1299;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_139)) begin
        row_reg_392 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12)))) begin
        ap_reg_ppstg_buff_C_val_0_1_reg_1376_pp0_it4 <= buff_C_val_0_1_reg_1376;
        ap_reg_ppstg_buff_C_val_1_1_reg_1382_pp0_it4 <= buff_C_val_1_1_reg_1382;
        ap_reg_ppstg_buff_C_val_2_1_reg_1388_pp0_it4 <= buff_C_val_2_1_reg_1388;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it10 <= ap_reg_ppstg_or_cond3_reg_1357_pp0_it9;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it11 <= ap_reg_ppstg_or_cond3_reg_1357_pp0_it10;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it2 <= ap_reg_ppstg_or_cond3_reg_1357_pp0_it1;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it3 <= ap_reg_ppstg_or_cond3_reg_1357_pp0_it2;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it4 <= ap_reg_ppstg_or_cond3_reg_1357_pp0_it3;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it5 <= ap_reg_ppstg_or_cond3_reg_1357_pp0_it4;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it6 <= ap_reg_ppstg_or_cond3_reg_1357_pp0_it5;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it7 <= ap_reg_ppstg_or_cond3_reg_1357_pp0_it6;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it8 <= ap_reg_ppstg_or_cond3_reg_1357_pp0_it7;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it9 <= ap_reg_ppstg_or_cond3_reg_1357_pp0_it8;
        ap_reg_ppstg_or_cond4_reg_1371_pp0_it10 <= ap_reg_ppstg_or_cond4_reg_1371_pp0_it9;
        ap_reg_ppstg_or_cond4_reg_1371_pp0_it11 <= ap_reg_ppstg_or_cond4_reg_1371_pp0_it10;
        ap_reg_ppstg_or_cond4_reg_1371_pp0_it3 <= or_cond4_reg_1371;
        ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 <= ap_reg_ppstg_or_cond4_reg_1371_pp0_it3;
        ap_reg_ppstg_or_cond4_reg_1371_pp0_it5 <= ap_reg_ppstg_or_cond4_reg_1371_pp0_it4;
        ap_reg_ppstg_or_cond4_reg_1371_pp0_it6 <= ap_reg_ppstg_or_cond4_reg_1371_pp0_it5;
        ap_reg_ppstg_or_cond4_reg_1371_pp0_it7 <= ap_reg_ppstg_or_cond4_reg_1371_pp0_it6;
        ap_reg_ppstg_or_cond4_reg_1371_pp0_it8 <= ap_reg_ppstg_or_cond4_reg_1371_pp0_it7;
        ap_reg_ppstg_or_cond4_reg_1371_pp0_it9 <= ap_reg_ppstg_or_cond4_reg_1371_pp0_it8;
        ap_reg_ppstg_tmp_11_reg_1333_pp0_it2 <= ap_reg_ppstg_tmp_11_reg_1333_pp0_it1;
        ap_reg_ppstg_tmp_1_reg_1324_pp0_it2 <= ap_reg_ppstg_tmp_1_reg_1324_pp0_it1;
        ap_reg_ppstg_tmp_1_reg_1324_pp0_it3 <= ap_reg_ppstg_tmp_1_reg_1324_pp0_it2;
        buff_C_val_0_1_reg_1376 <= buff_C_val_0_0_s_fu_134;
        buff_C_val_1_1_reg_1382 <= buff_C_val_1_0_s_fu_146;
        buff_C_val_2_1_reg_1388 <= buff_C_val_2_0_s_fu_158;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        ap_reg_ppstg_col_assign_reg_403_pp0_it1 <= col_assign_reg_403;
        ap_reg_ppstg_or_cond3_reg_1357_pp0_it1 <= or_cond3_reg_1357;
        ap_reg_ppstg_or_cond_reg_1353_pp0_it1 <= or_cond_reg_1353;
        ap_reg_ppstg_tmp_11_reg_1333_pp0_it1 <= tmp_11_reg_1333;
        ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 <= tmp_1_reg_1324;
        tmp_1_reg_1324 <= tmp_1_fu_645_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == tmp_1_fu_645_p2) & ~(ap_const_lv1_0 == tmp_11_fu_656_p2))) begin
        buff_A_val_1_addr_reg_1342 <= tmp_12_fu_661_p1;
        tmp_12_reg_1337[0] <= tmp_12_fu_661_p1[0];
tmp_12_reg_1337[1] <= tmp_12_fu_661_p1[1];
tmp_12_reg_1337[2] <= tmp_12_fu_661_p1[2];
tmp_12_reg_1337[3] <= tmp_12_fu_661_p1[3];
tmp_12_reg_1337[4] <= tmp_12_fu_661_p1[4];
tmp_12_reg_1337[5] <= tmp_12_fu_661_p1[5];
tmp_12_reg_1337[6] <= tmp_12_fu_661_p1[6];
tmp_12_reg_1337[7] <= tmp_12_fu_661_p1[7];
tmp_12_reg_1337[8] <= tmp_12_fu_661_p1[8];
tmp_12_reg_1337[9] <= tmp_12_fu_661_p1[9];
tmp_12_reg_1337[10] <= tmp_12_fu_661_p1[10];
tmp_12_reg_1337[11] <= tmp_12_fu_661_p1[11];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_reg_1353_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        buff_C_val_0_0_1_fu_142 <= src_data_stream_0_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1324_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_11_reg_1333_pp0_it2))) begin
        buff_C_val_0_0_s_fu_134 <= buff_C_val_0_0_1_fu_142;
        buff_C_val_1_0_s_fu_146 <= buff_C_val_1_0_1_load_reg_1361;
        buff_C_val_2_0_s_fu_158 <= buff_A_val_2_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1324_pp0_it3))) begin
        buff_C_val_0_1_s_fu_138 <= buff_C_val_0_1_reg_1376;
        buff_C_val_1_1_s_fu_150 <= buff_C_val_1_1_reg_1382;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(tmp_1_reg_1324 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_11_reg_1333))) begin
        buff_C_val_1_0_1_fu_130 <= buff_A_val_0_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 == ap_const_lv1_0) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_11_reg_1333_pp0_it1))) begin
        buff_C_val_1_0_1_load_reg_1361 <= buff_C_val_1_0_1_fu_130;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it3))) begin
        buff_C_val_1_0_load_reg_1398 <= buff_C_val_1_0_s_fu_146;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1324_pp0_it2))) begin
        buff_C_val_2_1_s_fu_154 <= buff_C_val_2_0_s_fu_158;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        col_reg_1328 <= col_fu_650_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_139)) begin
        cols_cast2_cast_reg_1175[0] <= cols_cast2_cast_fu_416_p1[0];
cols_cast2_cast_reg_1175[1] <= cols_cast2_cast_fu_416_p1[1];
cols_cast2_cast_reg_1175[2] <= cols_cast2_cast_fu_416_p1[2];
cols_cast2_cast_reg_1175[3] <= cols_cast2_cast_fu_416_p1[3];
cols_cast2_cast_reg_1175[4] <= cols_cast2_cast_fu_416_p1[4];
cols_cast2_cast_reg_1175[5] <= cols_cast2_cast_fu_416_p1[5];
cols_cast2_cast_reg_1175[6] <= cols_cast2_cast_fu_416_p1[6];
cols_cast2_cast_reg_1175[7] <= cols_cast2_cast_fu_416_p1[7];
cols_cast2_cast_reg_1175[8] <= cols_cast2_cast_fu_416_p1[8];
cols_cast2_cast_reg_1175[9] <= cols_cast2_cast_fu_416_p1[9];
cols_cast2_cast_reg_1175[10] <= cols_cast2_cast_fu_416_p1[10];
        rows_cast1_cast_reg_1180[0] <= rows_cast1_cast_fu_420_p1[0];
rows_cast1_cast_reg_1180[1] <= rows_cast1_cast_fu_420_p1[1];
rows_cast1_cast_reg_1180[2] <= rows_cast1_cast_fu_420_p1[2];
rows_cast1_cast_reg_1180[3] <= rows_cast1_cast_fu_420_p1[3];
rows_cast1_cast_reg_1180[4] <= rows_cast1_cast_fu_420_p1[4];
rows_cast1_cast_reg_1180[5] <= rows_cast1_cast_fu_420_p1[5];
rows_cast1_cast_reg_1180[6] <= rows_cast1_cast_fu_420_p1[6];
rows_cast1_cast_reg_1180[7] <= rows_cast1_cast_fu_420_p1[7];
rows_cast1_cast_reg_1180[8] <= rows_cast1_cast_fu_420_p1[8];
rows_cast1_cast_reg_1180[9] <= rows_cast1_cast_fu_420_p1[9];
rows_cast1_cast_reg_1180[10] <= rows_cast1_cast_fu_420_p1[10];
        tmp_33_i_reg_1290 <= tmp_33_i_fu_592_p2;
        tmp_36_0_1_i_reg_1215 <= tmp_36_0_1_i_fu_532_p1;
        tmp_36_0_2_i_reg_1225 <= tmp_36_0_2_i_fu_540_p1;
        tmp_36_0_i_reg_1205 <= tmp_36_0_i_fu_524_p1;
        tmp_36_1_1_i_reg_1245 <= tmp_36_1_1_i_fu_556_p1;
        tmp_36_1_2_i_reg_1255 <= tmp_36_1_2_i_fu_564_p1;
        tmp_36_1_i_reg_1235 <= tmp_36_1_i_fu_548_p1;
        tmp_36_2_1_i_reg_1275 <= tmp_36_2_1_i_fu_580_p1;
        tmp_36_2_2_i_reg_1285 <= tmp_36_2_2_i_fu_588_p1;
        tmp_36_2_i_reg_1265 <= tmp_36_2_i_fu_572_p1;
        tmp_38_0_1_i_reg_1220 <= tmp_38_0_1_i_fu_536_p1;
        tmp_38_0_2_i_reg_1230 <= tmp_38_0_2_i_fu_544_p1;
        tmp_38_0_i_reg_1210 <= tmp_38_0_i_fu_528_p1;
        tmp_38_1_1_i_reg_1250 <= tmp_38_1_1_i_fu_560_p1;
        tmp_38_1_2_i_reg_1260 <= tmp_38_1_2_i_fu_568_p1;
        tmp_38_1_i_reg_1240 <= tmp_38_1_i_fu_552_p1;
        tmp_38_2_1_i_reg_1280 <= tmp_38_2_1_i_fu_584_p1;
        tmp_38_2_i_reg_1270 <= tmp_38_2_i_fu_576_p1;
        tmp_5_cast_reg_1195 <= tmp_5_cast_fu_442_p1;
        tmp_6_cast_reg_1200 <= tmp_6_cast_fu_452_p1;
        tmp_reg_1185 <= tmp_fu_424_p2;
        tmp_s_reg_1190 <= tmp_s_fu_430_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it9))) begin
        edge_val1_i_reg_1561 <= edge_val1_i_fu_1053_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it10))) begin
        edge_val_2_i_reg_1567 <= edge_val_2_i_fu_1088_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it8))) begin
        edge_weight_reg_1551 <= edge_weight_fu_1033_p2;
        tmp_40_reg_1556 <= tmp_40_fu_1039_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == tmp_7_fu_602_p2))) begin
        icmp_reg_1309 <= icmp_fu_628_p2;
        tmp_3_reg_1314 <= tmp_3_fu_634_p2;
        tmp_4_reg_1319 <= tmp_4_fu_640_p2;
        tmp_8_reg_1304 <= tmp_8_fu_613_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_lv1_0 == tmp_1_fu_645_p2))) begin
        or_cond3_reg_1357 <= or_cond3_fu_678_p2;
        or_cond_reg_1353 <= or_cond_fu_667_p2;
        tmp_11_reg_1333 <= tmp_11_fu_656_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 == ap_const_lv1_0) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        or_cond4_reg_1371 <= or_cond4_fu_741_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        row_1_reg_1299 <= row_1_fu_607_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it6))) begin
        tmp10_reg_1517 <= tmp10_fu_951_p2;
        tmp11_reg_1522 <= tmp11_fu_956_p2;
        tmp13_reg_1527 <= tmp13_fu_961_p2;
        tmp15_reg_1532 <= tmp15_fu_966_p2;
        tmp3_reg_1497 <= tmp3_fu_931_p2;
        tmp4_reg_1502 <= tmp4_fu_936_p2;
        tmp6_reg_1507 <= tmp6_fu_941_p2;
        tmp8_reg_1512 <= tmp8_fu_946_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5))) begin
        tmp14_reg_1492 <= tmp14_fu_926_p2;
        tmp7_reg_1487 <= tmp7_fu_921_p2;
        tmp_37_0_i_reg_1457 <= grp_fu_809_p2;
        tmp_37_1_2_i_reg_1467 <= grp_fu_837_p2;
        tmp_37_2_i_reg_1477 <= grp_fu_851_p2;
        tmp_39_0_i_reg_1462 <= grp_fu_814_p2;
        tmp_39_1_2_i_reg_1472 <= grp_fu_842_p2;
        tmp_39_2_i_reg_1482 <= grp_fu_856_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4))) begin
        tmp_37_2_2_i_reg_1451 <= grp_fu_780_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it7))) begin
        x_weight_2_2_2_i_reg_1537 <= x_weight_2_2_2_i_fu_979_p2;
        y_weight_2_2_2_i_reg_1544 <= y_weight_2_2_2_i_fu_993_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or tmp_7_fu_602_p2 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == tmp_7_fu_602_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (tmp_7_fu_602_p2 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == tmp_7_fu_602_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_2 assign process. ///
always @ (ap_sig_bdd_75)
begin
    if (ap_sig_bdd_75) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_22)
begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_199)
begin
    if (ap_sig_bdd_199) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// buff_A_val_0_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        buff_A_val_0_ce0 = ap_const_logic_1;
    end else begin
        buff_A_val_0_ce0 = ap_const_logic_0;
    end
end

/// buff_A_val_0_ce1 assign process. ///
always @ (ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        buff_A_val_0_ce1 = ap_const_logic_1;
    end else begin
        buff_A_val_0_ce1 = ap_const_logic_0;
    end
end

/// buff_A_val_0_we1 assign process. ///
always @ (ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 or ap_reg_ppstg_or_cond_reg_1353_pp0_it1 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if ((~(ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_reg_1353_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        buff_A_val_0_we1 = ap_const_logic_1;
    end else begin
        buff_A_val_0_we1 = ap_const_logic_0;
    end
end

/// buff_A_val_1_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        buff_A_val_1_ce0 = ap_const_logic_1;
    end else begin
        buff_A_val_1_ce0 = ap_const_logic_0;
    end
end

/// buff_A_val_1_ce1 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        buff_A_val_1_ce1 = ap_const_logic_1;
    end else begin
        buff_A_val_1_ce1 = ap_const_logic_0;
    end
end

/// buff_A_val_1_we1 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it1 or tmp_1_reg_1324 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or tmp_11_reg_1333)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(tmp_1_reg_1324 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_11_reg_1333))) begin
        buff_A_val_1_we1 = ap_const_logic_1;
    end else begin
        buff_A_val_1_we1 = ap_const_logic_0;
    end
end

/// buff_A_val_2_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        buff_A_val_2_ce0 = ap_const_logic_1;
    end else begin
        buff_A_val_2_ce0 = ap_const_logic_0;
    end
end

/// buff_A_val_2_ce1 assign process. ///
always @ (ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        buff_A_val_2_ce1 = ap_const_logic_1;
    end else begin
        buff_A_val_2_ce1 = ap_const_logic_0;
    end
end

/// buff_A_val_2_we0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it1 or tmp_1_reg_1324 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or tmp_11_reg_1333)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(tmp_1_reg_1324 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_11_reg_1333))) begin
        buff_A_val_2_we0 = ap_const_logic_1;
    end else begin
        buff_A_val_2_we0 = ap_const_logic_0;
    end
end

/// col_assign_phi_fu_407_p4 assign process. ///
always @ (col_assign_reg_403 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it1 or tmp_1_reg_1324 or col_reg_1328)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(tmp_1_reg_1324 == ap_const_lv1_0))) begin
        col_assign_phi_fu_407_p4 = col_reg_1328;
    end else begin
        col_assign_phi_fu_407_p4 = col_assign_reg_403;
    end
end

/// dst_data_stream_0_V_write assign process. ///
always @ (ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_or_cond3_reg_1357_pp0_it11 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1357_pp0_it11) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        dst_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// dst_data_stream_1_V_write assign process. ///
always @ (ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_or_cond3_reg_1357_pp0_it11 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1357_pp0_it11) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        dst_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// grp_fu_780_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_tmp_1_reg_1324_pp0_it2 or or_cond4_reg_1371 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it3 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1324_pp0_it2) & (ap_const_lv1_0 == or_cond4_reg_1371)) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4)))) begin
        grp_fu_780_ce = ap_const_logic_1;
    end else begin
        grp_fu_780_ce = ap_const_logic_0;
    end
end

/// grp_fu_809_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it3 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)))) begin
        grp_fu_809_ce = ap_const_logic_1;
    end else begin
        grp_fu_809_ce = ap_const_logic_0;
    end
end

/// grp_fu_814_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it3 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)))) begin
        grp_fu_814_ce = ap_const_logic_1;
    end else begin
        grp_fu_814_ce = ap_const_logic_0;
    end
end

/// grp_fu_823_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it3 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)))) begin
        grp_fu_823_ce = ap_const_logic_1;
    end else begin
        grp_fu_823_ce = ap_const_logic_0;
    end
end

/// grp_fu_828_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it3 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)))) begin
        grp_fu_828_ce = ap_const_logic_1;
    end else begin
        grp_fu_828_ce = ap_const_logic_0;
    end
end

/// grp_fu_837_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it3 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)))) begin
        grp_fu_837_ce = ap_const_logic_1;
    end else begin
        grp_fu_837_ce = ap_const_logic_0;
    end
end

/// grp_fu_842_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it3 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)))) begin
        grp_fu_842_ce = ap_const_logic_1;
    end else begin
        grp_fu_842_ce = ap_const_logic_0;
    end
end

/// grp_fu_851_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it3 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)))) begin
        grp_fu_851_ce = ap_const_logic_1;
    end else begin
        grp_fu_851_ce = ap_const_logic_0;
    end
end

/// grp_fu_856_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it3 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5)))) begin
        grp_fu_856_ce = ap_const_logic_1;
    end else begin
        grp_fu_856_ce = ap_const_logic_0;
    end
end

/// grp_fu_872_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)))) begin
        grp_fu_872_ce = ap_const_logic_1;
    end else begin
        grp_fu_872_ce = ap_const_logic_0;
    end
end

/// grp_fu_877_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)))) begin
        grp_fu_877_ce = ap_const_logic_1;
    end else begin
        grp_fu_877_ce = ap_const_logic_0;
    end
end

/// grp_fu_885_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)))) begin
        grp_fu_885_ce = ap_const_logic_1;
    end else begin
        grp_fu_885_ce = ap_const_logic_0;
    end
end

/// grp_fu_890_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)))) begin
        grp_fu_890_ce = ap_const_logic_1;
    end else begin
        grp_fu_890_ce = ap_const_logic_0;
    end
end

/// grp_fu_898_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)))) begin
        grp_fu_898_ce = ap_const_logic_1;
    end else begin
        grp_fu_898_ce = ap_const_logic_0;
    end
end

/// grp_fu_903_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)))) begin
        grp_fu_903_ce = ap_const_logic_1;
    end else begin
        grp_fu_903_ce = ap_const_logic_0;
    end
end

/// grp_fu_911_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)))) begin
        grp_fu_911_ce = ap_const_logic_1;
    end else begin
        grp_fu_911_ce = ap_const_logic_0;
    end
end

/// grp_fu_916_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it4 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it5 or ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ((ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it4) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it5) | (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_reg_1371_pp0_it6)))) begin
        grp_fu_916_ce = ap_const_logic_1;
    end else begin
        grp_fu_916_ce = ap_const_logic_0;
    end
end

/// src_data_stream_0_V_read assign process. ///
always @ (ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 or ap_reg_ppstg_or_cond_reg_1353_pp0_it1 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if ((~(ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_reg_1353_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// src_data_stream_1_V_read assign process. ///
always @ (ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 or ap_reg_ppstg_or_cond_reg_1353_pp0_it1 or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12)
begin
    if ((~(ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_reg_1353_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))))) begin
        src_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_1_V_read = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or ap_sig_bdd_96 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it11 or ap_sig_bdd_127 or ap_reg_ppiten_pp0_it12 or ap_sig_bdd_139 or tmp_7_fu_602_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_139) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((ap_const_lv1_0 == tmp_7_fu_602_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it12) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it11)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it12) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it11)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_96 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_127 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it12))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_sig_bdd_127 assign process. ///
always @ (dst_data_stream_0_V_full_n or dst_data_stream_1_V_full_n or ap_reg_ppstg_or_cond3_reg_1357_pp0_it11)
begin
    ap_sig_bdd_127 = (((dst_data_stream_0_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1357_pp0_it11)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond3_reg_1357_pp0_it11) & (dst_data_stream_1_V_full_n == ap_const_logic_0)));
end

/// ap_sig_bdd_139 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_139 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_199 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_199 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_22 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_75 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_75 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_96 assign process. ///
always @ (src_data_stream_0_V_empty_n or src_data_stream_1_V_empty_n or ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 or ap_reg_ppstg_or_cond_reg_1353_pp0_it1)
begin
    ap_sig_bdd_96 = (((src_data_stream_0_V_empty_n == ap_const_logic_0) & ~(ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_reg_1353_pp0_it1)) | (~(ap_reg_ppstg_tmp_1_reg_1324_pp0_it1 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_reg_1353_pp0_it1) & (src_data_stream_1_V_empty_n == ap_const_logic_0)));
end
assign buff_A_val_0_address0 = tmp_12_fu_661_p1;
assign buff_A_val_0_address1 = tmp_15_fu_692_p1;
assign buff_A_val_0_d1 = src_data_stream_0_V_dout;
assign buff_A_val_1_address0 = tmp_12_fu_661_p1;
assign buff_A_val_1_address1 = buff_A_val_1_addr_reg_1342;
assign buff_A_val_1_d1 = buff_A_val_0_q0;
assign buff_A_val_2_address0 = tmp_12_reg_1337;
assign buff_A_val_2_address1 = tmp_17_fu_705_p1;
assign buff_A_val_2_d0 = buff_A_val_1_q0;
assign col_assign_cast_cast_fu_688_p1 = ap_reg_ppstg_col_assign_reg_403_pp0_it1;
assign col_fu_650_p2 = (col_assign_phi_fu_407_p4 + ap_const_lv12_1);
assign cols_cast2_cast_fu_416_p1 = cols;
assign dst_data_stream_0_V_din = ((ap_reg_ppstg_or_cond4_reg_1371_pp0_it11)? ap_const_lv8_0: edge_val_3_fu_1100_p3);
assign dst_data_stream_1_V_din = ap_const_lv8_80;
assign edge_val1_i_fu_1053_p3 = ((tmp_23_i_fu_1043_p2)? edge_val_fu_1048_p2: ap_const_lv8_0);
assign edge_val_1_fu_1095_p2 = (edge_val_2_i_reg_1567 ^ ap_const_lv8_FF);
assign edge_val_2_i_fu_1088_p3 = ((tmp_21_fu_1082_p2)? p_edge_val_i_fu_1074_p3: edge_val1_i_reg_1561);
assign edge_val_3_fu_1100_p3 = ((tmp_33_i_reg_1290)? edge_val_1_fu_1095_p2: edge_val_2_i_reg_1567);
assign edge_val_fu_1048_p2 = (tmp_40_reg_1556 ^ ap_const_lv8_FF);
assign edge_weight_fu_1033_p2 = (tmp_19_i_fu_1009_p3 + tmp_22_i_fu_1026_p3);
assign grp_fu_780_p0 = tmp_36_2_2_i_reg_1285;
assign grp_fu_780_p1 = grp_fu_780_p10;
assign grp_fu_780_p10 = buff_C_val_2_1_s_fu_154;
assign grp_fu_809_p0 = tmp_36_0_i_reg_1205;
assign grp_fu_809_p1 = tmp_35_0_i_fu_805_p1;
assign grp_fu_814_p0 = tmp_38_0_i_reg_1210;
assign grp_fu_814_p1 = tmp_35_0_i_fu_805_p1;
assign grp_fu_823_p0 = tmp_36_0_2_i_reg_1225;
assign grp_fu_823_p1 = tmp_35_0_2_i_fu_819_p1;
assign grp_fu_828_p0 = tmp_38_0_2_i_reg_1230;
assign grp_fu_828_p1 = tmp_35_0_2_i_fu_819_p1;
assign grp_fu_837_p0 = tmp_36_1_2_i_reg_1255;
assign grp_fu_837_p1 = tmp_35_1_2_i_fu_833_p1;
assign grp_fu_842_p0 = tmp_38_1_2_i_reg_1260;
assign grp_fu_842_p1 = tmp_35_1_2_i_fu_833_p1;
assign grp_fu_851_p0 = tmp_36_2_i_reg_1265;
assign grp_fu_851_p1 = tmp_35_2_i_fu_847_p1;
assign grp_fu_856_p0 = tmp_38_2_i_reg_1270;
assign grp_fu_856_p1 = tmp_35_2_i_fu_847_p1;
assign grp_fu_872_p0 = tmp_36_0_1_i_reg_1215;
assign grp_fu_872_p1 = tmp_35_0_1_i_fu_869_p1;
assign grp_fu_877_p0 = tmp_38_0_1_i_reg_1220;
assign grp_fu_877_p1 = tmp_35_0_1_i_fu_869_p1;
assign grp_fu_885_p0 = tmp_36_1_i_reg_1235;
assign grp_fu_885_p1 = tmp_35_1_i_fu_882_p1;
assign grp_fu_890_p0 = tmp_38_1_i_reg_1240;
assign grp_fu_890_p1 = tmp_35_1_i_fu_882_p1;
assign grp_fu_898_p0 = tmp_36_1_1_i_reg_1245;
assign grp_fu_898_p1 = tmp_35_1_1_i_fu_895_p1;
assign grp_fu_903_p0 = tmp_38_1_1_i_reg_1250;
assign grp_fu_903_p1 = tmp_35_1_1_i_fu_895_p1;
assign grp_fu_911_p0 = tmp_36_2_1_i_reg_1275;
assign grp_fu_911_p1 = tmp_35_2_1_i_fu_908_p1;
assign grp_fu_916_p0 = tmp_38_2_1_i_reg_1280;
assign grp_fu_916_p1 = tmp_35_2_1_i_fu_908_p1;
assign icmp1_fu_720_p2 = (tmp_39_fu_710_p4 == ap_const_lv11_0? 1'b1: 1'b0);
assign icmp_fu_628_p2 = (tmp_37_fu_618_p4 == ap_const_lv11_0? 1'b1: 1'b0);
assign or_cond3_fu_678_p2 = (tmp_3_reg_1314 & tmp_23_fu_672_p2);
assign or_cond4_fu_741_p2 = (tmp2_fu_736_p2 | tmp1_fu_731_p2);
assign or_cond_fu_667_p2 = (tmp_11_fu_656_p2 & tmp_8_reg_1304);
assign p_edge_val_i_fu_1074_p3 = ((tmp_27_i_fu_1064_p2)? ap_const_lv8_FF: ap_const_lv8_0);
assign row_1_fu_607_p2 = (row_reg_392 + ap_const_lv12_1);
assign row_cast_cast_fu_598_p1 = row_reg_392;
assign rows_cast1_cast_fu_420_p1 = rows;
assign tmp10_fu_951_p2 = ($signed(tmp_39_2_i_reg_1482) + $signed(grp_fu_916_p2));
assign tmp11_fu_956_p2 = ($signed(tmp_39_1_2_i_reg_1472) + $signed(grp_fu_903_p2));
assign tmp12_fu_985_p2 = ($signed(tmp11_reg_1522) + $signed(tmp10_reg_1517));
assign tmp13_fu_961_p2 = ($signed(tmp_39_0_i_reg_1462) + $signed(grp_fu_877_p2));
assign tmp14_fu_926_p2 = ($signed(grp_fu_828_p2) + $signed(tmp_37_2_2_i_reg_1451));
assign tmp15_fu_966_p2 = ($signed(tmp14_reg_1492) + $signed(grp_fu_890_p2));
assign tmp16_fu_989_p2 = ($signed(tmp15_reg_1532) + $signed(tmp13_reg_1527));
assign tmp1_fu_731_p2 = (icmp_reg_1309 | icmp1_fu_720_p2);
assign tmp2_fu_736_p2 = (tmp_4_reg_1319 | tmp_19_fu_726_p2);
assign tmp3_fu_931_p2 = ($signed(tmp_37_2_i_reg_1477) + $signed(grp_fu_911_p2));
assign tmp4_fu_936_p2 = ($signed(tmp_37_1_2_i_reg_1467) + $signed(grp_fu_898_p2));
assign tmp5_fu_971_p2 = ($signed(tmp4_reg_1502) + $signed(tmp3_reg_1497));
assign tmp6_fu_941_p2 = ($signed(tmp_37_0_i_reg_1457) + $signed(grp_fu_872_p2));
assign tmp7_fu_921_p2 = ($signed(grp_fu_823_p2) + $signed(tmp_37_2_2_i_reg_1451));
assign tmp8_fu_946_p2 = ($signed(tmp7_reg_1487) + $signed(grp_fu_885_p2));
assign tmp9_fu_975_p2 = ($signed(tmp8_reg_1512) + $signed(tmp6_reg_1507));
assign tmp_11_fu_656_p2 = (col_assign_phi_fu_407_p4 < cols_cast2_cast_reg_1175? 1'b1: 1'b0);
assign tmp_12_fu_661_p1 = col_assign_phi_fu_407_p4;
assign tmp_13_fu_464_p1 = C_XR0C2[7:0];
assign tmp_15_fu_692_p1 = ap_reg_ppstg_col_assign_reg_403_pp0_it1;
assign tmp_16_fu_468_p1 = C_XR1C0[7:0];
assign tmp_17_fu_705_p1 = ap_reg_ppstg_col_assign_reg_403_pp0_it1;
assign tmp_17_i_fu_999_p2 = ($signed(x_weight_2_2_2_i_reg_1537) > $signed(16'b0000000000000000)? 1'b1: 1'b0);
assign tmp_18_fu_472_p1 = C_XR1C1[7:0];
assign tmp_18_i_fu_1004_p2 = ($signed(ap_const_lv16_0) - $signed(x_weight_2_2_2_i_reg_1537));
assign tmp_19_fu_726_p2 = ($signed(col_assign_cast_cast_fu_688_p1) > $signed(tmp_6_cast_reg_1200)? 1'b1: 1'b0);
assign tmp_19_i_fu_1009_p3 = ((tmp_17_i_fu_999_p2)? x_weight_2_2_2_i_reg_1537: tmp_18_i_fu_1004_p2);
assign tmp_1_fu_645_p2 = (col_assign_phi_fu_407_p4 < tmp_s_reg_1190? 1'b1: 1'b0);
assign tmp_20_fu_476_p1 = C_XR1C2[7:0];
assign tmp_20_i_fu_1016_p2 = ($signed(y_weight_2_2_2_i_reg_1544) > $signed(16'b0000000000000000)? 1'b1: 1'b0);
assign tmp_21_fu_1082_p2 = (tmp_27_i_fu_1064_p2 | tmp_28_i_fu_1069_p2);
assign tmp_21_i_fu_1021_p2 = ($signed(ap_const_lv16_0) - $signed(y_weight_2_2_2_i_reg_1544));
assign tmp_22_i_fu_1026_p3 = ((tmp_20_i_fu_1016_p2)? y_weight_2_2_2_i_reg_1544: tmp_21_i_fu_1021_p2);
assign tmp_23_fu_672_p2 = (col_assign_phi_fu_407_p4 != ap_const_lv12_0? 1'b1: 1'b0);
assign tmp_23_i_fu_1043_p2 = ($signed(edge_weight_reg_1551) < $signed(16'b11111111)? 1'b1: 1'b0);
assign tmp_26_fu_480_p1 = C_XR2C0[7:0];
assign tmp_26_i_fu_1061_p1 = edge_val1_i_reg_1561;
assign tmp_27_fu_484_p1 = C_XR2C1[7:0];
assign tmp_27_i_fu_1064_p2 = ($signed(tmp_26_i_fu_1061_p1) > $signed(c_high_thresh)? 1'b1: 1'b0);
assign tmp_28_fu_488_p1 = C_XR2C2[7:0];
assign tmp_28_i_fu_1069_p2 = ($signed(tmp_26_i_fu_1061_p1) < $signed(c_low_thresh)? 1'b1: 1'b0);
assign tmp_29_fu_492_p1 = C_YR0C0[7:0];
assign tmp_2_fu_456_p1 = C_XR0C0[7:0];
assign tmp_30_fu_496_p1 = C_YR0C1[7:0];
assign tmp_31_fu_500_p1 = C_YR0C2[7:0];
assign tmp_32_fu_504_p1 = C_YR1C0[7:0];
assign tmp_33_fu_508_p1 = C_YR1C1[7:0];
assign tmp_33_i_fu_592_p2 = (c_invert == ap_const_lv32_1? 1'b1: 1'b0);
assign tmp_34_fu_512_p1 = C_YR1C2[7:0];
assign tmp_35_0_1_i_fu_869_p1 = ap_reg_ppstg_buff_C_val_0_1_reg_1376_pp0_it4;
assign tmp_35_0_2_i_fu_819_p1 = buff_C_val_0_1_s_fu_138;
assign tmp_35_0_i_fu_805_p1 = buff_C_val_0_0_s_fu_134;
assign tmp_35_1_1_i_fu_895_p1 = ap_reg_ppstg_buff_C_val_1_1_reg_1382_pp0_it4;
assign tmp_35_1_2_i_fu_833_p1 = buff_C_val_1_1_s_fu_150;
assign tmp_35_1_i_fu_882_p1 = buff_C_val_1_0_load_reg_1398;
assign tmp_35_2_1_i_fu_908_p1 = ap_reg_ppstg_buff_C_val_2_1_reg_1388_pp0_it4;
assign tmp_35_2_i_fu_847_p1 = buff_C_val_2_0_s_fu_158;
assign tmp_35_fu_516_p1 = C_YR2C0[7:0];
assign tmp_36_0_1_i_fu_532_p1 = $signed(tmp_9_fu_460_p1);
assign tmp_36_0_2_i_fu_540_p1 = $signed(tmp_13_fu_464_p1);
assign tmp_36_0_i_fu_524_p1 = $signed(tmp_2_fu_456_p1);
assign tmp_36_1_1_i_fu_556_p1 = $signed(tmp_18_fu_472_p1);
assign tmp_36_1_2_i_fu_564_p1 = $signed(tmp_20_fu_476_p1);
assign tmp_36_1_i_fu_548_p1 = $signed(tmp_16_fu_468_p1);
assign tmp_36_2_1_i_fu_580_p1 = $signed(tmp_27_fu_484_p1);
assign tmp_36_2_2_i_fu_588_p1 = $signed(tmp_28_fu_488_p1);
assign tmp_36_2_i_fu_572_p1 = $signed(tmp_26_fu_480_p1);
assign tmp_36_fu_520_p1 = C_YR2C1[7:0];
assign tmp_37_fu_618_p4 = {{row_reg_392[ap_const_lv32_B : ap_const_lv32_1]}};
assign tmp_38_0_1_i_fu_536_p1 = $signed(tmp_30_fu_496_p1);
assign tmp_38_0_2_i_fu_544_p1 = $signed(tmp_31_fu_500_p1);
assign tmp_38_0_i_fu_528_p1 = $signed(tmp_29_fu_492_p1);
assign tmp_38_1_1_i_fu_560_p1 = $signed(tmp_33_fu_508_p1);
assign tmp_38_1_2_i_fu_568_p1 = $signed(tmp_34_fu_512_p1);
assign tmp_38_1_i_fu_552_p1 = $signed(tmp_32_fu_504_p1);
assign tmp_38_2_1_i_fu_584_p1 = $signed(tmp_36_fu_520_p1);
assign tmp_38_2_i_fu_576_p1 = $signed(tmp_35_fu_516_p1);
assign tmp_39_fu_710_p4 = {{ap_reg_ppstg_col_assign_reg_403_pp0_it1[ap_const_lv32_B : ap_const_lv32_1]}};
assign tmp_3_fu_634_p2 = (row_reg_392 != ap_const_lv12_0? 1'b1: 1'b0);
assign tmp_40_fu_1039_p1 = edge_weight_fu_1033_p2[7:0];
assign tmp_4_fu_640_p2 = ($signed(row_cast_cast_fu_598_p1) > $signed(tmp_5_cast_reg_1195)? 1'b1: 1'b0);
assign tmp_5_cast_fu_442_p1 = $signed(tmp_5_fu_436_p2);
assign tmp_5_fu_436_p2 = ($signed(rows_cast1_cast_fu_420_p1) + $signed(ap_const_lv12_FFF));
assign tmp_6_cast_fu_452_p1 = $signed(tmp_6_fu_446_p2);
assign tmp_6_fu_446_p2 = ($signed(cols_cast2_cast_fu_416_p1) + $signed(ap_const_lv12_FFF));
assign tmp_7_fu_602_p2 = (row_reg_392 < tmp_reg_1185? 1'b1: 1'b0);
assign tmp_8_fu_613_p2 = (row_reg_392 < rows_cast1_cast_reg_1180? 1'b1: 1'b0);
assign tmp_9_fu_460_p1 = C_XR0C1[7:0];
assign tmp_fu_424_p2 = (rows_cast1_cast_fu_420_p1 + ap_const_lv12_1);
assign tmp_s_fu_430_p2 = (cols_cast2_cast_fu_416_p1 + ap_const_lv12_1);
assign x_weight_2_2_2_i_fu_979_p2 = ($signed(tmp9_fu_975_p2) + $signed(tmp5_fu_971_p2));
assign y_weight_2_2_2_i_fu_993_p2 = ($signed(tmp16_fu_989_p2) + $signed(tmp12_fu_985_p2));
always @ (posedge ap_clk)
begin
    cols_cast2_cast_reg_1175[11] <= 1'b0;
    rows_cast1_cast_reg_1180[11] <= 1'b0;
    tmp_12_reg_1337[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end



endmodule //image_filter_sobel_filter_core

