// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="image_filter,hls_ip_2014_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=6.666670,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.810000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=3,HLS_SYN_DSP=17,HLS_SYN_FF=2151,HLS_SYN_LUT=2695}" *)

module image_filter (
        s_axi_CONTROL_BUS_AWVALID,
        s_axi_CONTROL_BUS_AWREADY,
        s_axi_CONTROL_BUS_AWADDR,
        s_axi_CONTROL_BUS_WVALID,
        s_axi_CONTROL_BUS_WREADY,
        s_axi_CONTROL_BUS_WDATA,
        s_axi_CONTROL_BUS_WSTRB,
        s_axi_CONTROL_BUS_ARVALID,
        s_axi_CONTROL_BUS_ARREADY,
        s_axi_CONTROL_BUS_ARADDR,
        s_axi_CONTROL_BUS_RVALID,
        s_axi_CONTROL_BUS_RREADY,
        s_axi_CONTROL_BUS_RDATA,
        s_axi_CONTROL_BUS_RRESP,
        s_axi_CONTROL_BUS_BVALID,
        s_axi_CONTROL_BUS_BREADY,
        s_axi_CONTROL_BUS_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        video_in_TDATA,
        video_in_TKEEP,
        video_in_TSTRB,
        video_in_TUSER,
        video_in_TLAST,
        video_in_TID,
        video_in_TDEST,
        video_out_TDATA,
        video_out_TKEEP,
        video_out_TSTRB,
        video_out_TUSER,
        video_out_TLAST,
        video_out_TID,
        video_out_TDEST,
        video_in_TVALID,
        video_in_TREADY,
        video_out_TVALID,
        video_out_TREADY
);

parameter    C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 8;
parameter    C_DATA_WIDTH = 32;
parameter    C_ADDR_WIDTH = 32;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_true = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_B = 32'b1011;
parameter    C_S_AXI_CONTROL_BUS_WSTRB_WIDTH = (C_S_AXI_CONTROL_BUS_DATA_WIDTH / ap_const_int64_8);
parameter    C_WSTRB_WIDTH = (C_DATA_WIDTH / ap_const_int64_8);

input   s_axi_CONTROL_BUS_AWVALID;
output   s_axi_CONTROL_BUS_AWREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1 : 0] s_axi_CONTROL_BUS_AWADDR;
input   s_axi_CONTROL_BUS_WVALID;
output   s_axi_CONTROL_BUS_WREADY;
input  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1 : 0] s_axi_CONTROL_BUS_WDATA;
input  [C_S_AXI_CONTROL_BUS_WSTRB_WIDTH - 1 : 0] s_axi_CONTROL_BUS_WSTRB;
input   s_axi_CONTROL_BUS_ARVALID;
output   s_axi_CONTROL_BUS_ARREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1 : 0] s_axi_CONTROL_BUS_ARADDR;
output   s_axi_CONTROL_BUS_RVALID;
input   s_axi_CONTROL_BUS_RREADY;
output  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1 : 0] s_axi_CONTROL_BUS_RDATA;
output  [1:0] s_axi_CONTROL_BUS_RRESP;
output   s_axi_CONTROL_BUS_BVALID;
input   s_axi_CONTROL_BUS_BREADY;
output  [1:0] s_axi_CONTROL_BUS_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [15:0] video_in_TDATA;
input  [1:0] video_in_TKEEP;
input  [1:0] video_in_TSTRB;
input  [0:0] video_in_TUSER;
input  [0:0] video_in_TLAST;
input  [0:0] video_in_TID;
input  [0:0] video_in_TDEST;
output  [15:0] video_out_TDATA;
output  [1:0] video_out_TKEEP;
output  [1:0] video_out_TSTRB;
output  [0:0] video_out_TUSER;
output  [0:0] video_out_TLAST;
output  [0:0] video_out_TID;
output  [0:0] video_out_TDEST;
input   video_in_TVALID;
output   video_in_TREADY;
output   video_out_TVALID;
input   video_out_TREADY;

reg    ap_rst_n_inv;
wire    image_filter_CONTROL_BUS_s_axi_U_ap_dummy_ce;
wire   [31:0] rows;
wire   [31:0] cols;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
reg    ap_idle;
wire   [31:0] C_XR0C0;
wire   [31:0] C_XR0C1;
wire   [31:0] C_XR0C2;
wire   [31:0] C_XR1C0;
wire   [31:0] C_XR1C1;
wire   [31:0] C_XR1C2;
wire   [31:0] C_XR2C0;
wire   [31:0] C_XR2C1;
wire   [31:0] C_XR2C2;
wire   [31:0] C_YR0C0;
wire   [31:0] C_YR0C1;
wire   [31:0] C_YR0C2;
wire   [31:0] C_YR1C0;
wire   [31:0] C_YR1C1;
wire   [31:0] C_YR1C2;
wire   [31:0] C_YR2C0;
wire   [31:0] C_YR2C1;
wire   [31:0] C_YR2C2;
wire   [31:0] c_high_thresh;
wire   [31:0] c_low_thresh;
wire   [31:0] c_invert;
wire    image_filter_Block_proc_U0_ap_start;
wire    image_filter_Block_proc_U0_ap_done;
reg    image_filter_Block_proc_U0_ap_continue;
wire    image_filter_Block_proc_U0_ap_idle;
wire    image_filter_Block_proc_U0_ap_ready;
wire   [31:0] image_filter_Block_proc_U0_rows;
wire   [31:0] image_filter_Block_proc_U0_cols;
wire   [11:0] image_filter_Block_proc_U0_ap_return_0;
wire   [11:0] image_filter_Block_proc_U0_ap_return_1;
wire   [11:0] image_filter_Block_proc_U0_ap_return_2;
wire   [11:0] image_filter_Block_proc_U0_ap_return_3;
reg    ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel;
wire    img_0_rows_V_channel_full_n;
reg    ap_reg_ready_img_0_rows_V_channel_full_n = 1'b0;
reg    ap_sig_ready_img_0_rows_V_channel_full_n;
reg    ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel;
wire    img_0_cols_V_channel_full_n;
reg    ap_reg_ready_img_0_cols_V_channel_full_n = 1'b0;
reg    ap_sig_ready_img_0_cols_V_channel_full_n;
reg    ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V;
wire    img_1_rows_V_full_n;
reg    ap_reg_ready_img_1_rows_V_full_n = 1'b0;
reg    ap_sig_ready_img_1_rows_V_full_n;
reg    ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V;
wire    img_1_cols_V_full_n;
reg    ap_reg_ready_img_1_cols_V_full_n = 1'b0;
reg    ap_sig_ready_img_1_cols_V_full_n;
wire    image_filter_AXIvideo2Mat_U0_ap_start;
wire    image_filter_AXIvideo2Mat_U0_ap_done;
wire    image_filter_AXIvideo2Mat_U0_ap_continue;
wire    image_filter_AXIvideo2Mat_U0_ap_idle;
wire    image_filter_AXIvideo2Mat_U0_ap_ready;
wire   [15:0] image_filter_AXIvideo2Mat_U0_video_in_TDATA;
wire    image_filter_AXIvideo2Mat_U0_video_in_TVALID;
wire    image_filter_AXIvideo2Mat_U0_video_in_TREADY;
wire   [1:0] image_filter_AXIvideo2Mat_U0_video_in_TKEEP;
wire   [1:0] image_filter_AXIvideo2Mat_U0_video_in_TSTRB;
wire   [0:0] image_filter_AXIvideo2Mat_U0_video_in_TUSER;
wire   [0:0] image_filter_AXIvideo2Mat_U0_video_in_TLAST;
wire   [0:0] image_filter_AXIvideo2Mat_U0_video_in_TID;
wire   [0:0] image_filter_AXIvideo2Mat_U0_video_in_TDEST;
wire   [11:0] image_filter_AXIvideo2Mat_U0_img_rows_V_read;
wire   [11:0] image_filter_AXIvideo2Mat_U0_img_cols_V_read;
wire   [7:0] image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n;
wire    image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n;
wire    image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire    image_filter_sobel_filter_core_U0_ap_start;
wire    image_filter_sobel_filter_core_U0_ap_done;
wire    image_filter_sobel_filter_core_U0_ap_continue;
wire    image_filter_sobel_filter_core_U0_ap_idle;
wire    image_filter_sobel_filter_core_U0_ap_ready;
wire   [7:0] image_filter_sobel_filter_core_U0_src_data_stream_0_V_dout;
wire    image_filter_sobel_filter_core_U0_src_data_stream_0_V_empty_n;
wire    image_filter_sobel_filter_core_U0_src_data_stream_0_V_read;
wire   [7:0] image_filter_sobel_filter_core_U0_src_data_stream_1_V_dout;
wire    image_filter_sobel_filter_core_U0_src_data_stream_1_V_empty_n;
wire    image_filter_sobel_filter_core_U0_src_data_stream_1_V_read;
wire   [7:0] image_filter_sobel_filter_core_U0_dst_data_stream_0_V_din;
wire    image_filter_sobel_filter_core_U0_dst_data_stream_0_V_full_n;
wire    image_filter_sobel_filter_core_U0_dst_data_stream_0_V_write;
wire   [7:0] image_filter_sobel_filter_core_U0_dst_data_stream_1_V_din;
wire    image_filter_sobel_filter_core_U0_dst_data_stream_1_V_full_n;
wire    image_filter_sobel_filter_core_U0_dst_data_stream_1_V_write;
wire   [10:0] image_filter_sobel_filter_core_U0_rows;
wire   [10:0] image_filter_sobel_filter_core_U0_cols;
wire   [31:0] image_filter_sobel_filter_core_U0_C_XR0C0;
wire   [31:0] image_filter_sobel_filter_core_U0_C_XR0C1;
wire   [31:0] image_filter_sobel_filter_core_U0_C_XR0C2;
wire   [31:0] image_filter_sobel_filter_core_U0_C_XR1C0;
wire   [31:0] image_filter_sobel_filter_core_U0_C_XR1C1;
wire   [31:0] image_filter_sobel_filter_core_U0_C_XR1C2;
wire   [31:0] image_filter_sobel_filter_core_U0_C_XR2C0;
wire   [31:0] image_filter_sobel_filter_core_U0_C_XR2C1;
wire   [31:0] image_filter_sobel_filter_core_U0_C_XR2C2;
wire   [31:0] image_filter_sobel_filter_core_U0_C_YR0C0;
wire   [31:0] image_filter_sobel_filter_core_U0_C_YR0C1;
wire   [31:0] image_filter_sobel_filter_core_U0_C_YR0C2;
wire   [31:0] image_filter_sobel_filter_core_U0_C_YR1C0;
wire   [31:0] image_filter_sobel_filter_core_U0_C_YR1C1;
wire   [31:0] image_filter_sobel_filter_core_U0_C_YR1C2;
wire   [31:0] image_filter_sobel_filter_core_U0_C_YR2C0;
wire   [31:0] image_filter_sobel_filter_core_U0_C_YR2C1;
wire   [31:0] image_filter_sobel_filter_core_U0_c_high_thresh;
wire   [31:0] image_filter_sobel_filter_core_U0_c_low_thresh;
wire   [31:0] image_filter_sobel_filter_core_U0_c_invert;
wire    image_filter_Mat2AXIvideo_U0_ap_start;
wire    image_filter_Mat2AXIvideo_U0_ap_done;
wire    image_filter_Mat2AXIvideo_U0_ap_continue;
wire    image_filter_Mat2AXIvideo_U0_ap_idle;
wire    image_filter_Mat2AXIvideo_U0_ap_ready;
wire   [11:0] image_filter_Mat2AXIvideo_U0_img_rows_V_read;
wire   [11:0] image_filter_Mat2AXIvideo_U0_img_cols_V_read;
wire   [7:0] image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_dout;
wire    image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n;
wire    image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_read;
wire   [7:0] image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_dout;
wire    image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n;
wire    image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_read;
wire   [15:0] image_filter_Mat2AXIvideo_U0_video_out_TDATA;
wire    image_filter_Mat2AXIvideo_U0_video_out_TVALID;
wire    image_filter_Mat2AXIvideo_U0_video_out_TREADY;
wire   [1:0] image_filter_Mat2AXIvideo_U0_video_out_TKEEP;
wire   [1:0] image_filter_Mat2AXIvideo_U0_video_out_TSTRB;
wire   [0:0] image_filter_Mat2AXIvideo_U0_video_out_TUSER;
wire   [0:0] image_filter_Mat2AXIvideo_U0_video_out_TLAST;
wire   [0:0] image_filter_Mat2AXIvideo_U0_video_out_TID;
wire   [0:0] image_filter_Mat2AXIvideo_U0_video_out_TDEST;
wire    ap_sig_hs_continue;
wire    img_0_rows_V_channel_U_ap_dummy_ce;
wire   [11:0] img_0_rows_V_channel_din;
wire    img_0_rows_V_channel_write;
wire   [11:0] img_0_rows_V_channel_dout;
wire    img_0_rows_V_channel_empty_n;
wire    img_0_rows_V_channel_read;
wire    img_0_cols_V_channel_U_ap_dummy_ce;
wire   [11:0] img_0_cols_V_channel_din;
wire    img_0_cols_V_channel_write;
wire   [11:0] img_0_cols_V_channel_dout;
wire    img_0_cols_V_channel_empty_n;
wire    img_0_cols_V_channel_read;
wire    img_1_rows_V_U_ap_dummy_ce;
wire   [11:0] img_1_rows_V_din;
wire    img_1_rows_V_write;
wire   [11:0] img_1_rows_V_dout;
wire    img_1_rows_V_empty_n;
wire    img_1_rows_V_read;
wire    img_1_cols_V_U_ap_dummy_ce;
wire   [11:0] img_1_cols_V_din;
wire    img_1_cols_V_write;
wire   [11:0] img_1_cols_V_dout;
wire    img_1_cols_V_empty_n;
wire    img_1_cols_V_read;
wire    img_0_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_0_V_din;
wire    img_0_data_stream_0_V_full_n;
wire    img_0_data_stream_0_V_write;
wire   [7:0] img_0_data_stream_0_V_dout;
wire    img_0_data_stream_0_V_empty_n;
wire    img_0_data_stream_0_V_read;
wire    img_0_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_1_V_din;
wire    img_0_data_stream_1_V_full_n;
wire    img_0_data_stream_1_V_write;
wire   [7:0] img_0_data_stream_1_V_dout;
wire    img_0_data_stream_1_V_empty_n;
wire    img_0_data_stream_1_V_read;
wire    img_1_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_1_data_stream_0_V_din;
wire    img_1_data_stream_0_V_full_n;
wire    img_1_data_stream_0_V_write;
wire   [7:0] img_1_data_stream_0_V_dout;
wire    img_1_data_stream_0_V_empty_n;
wire    img_1_data_stream_0_V_read;
wire    img_1_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_1_data_stream_1_V_din;
wire    img_1_data_stream_1_V_full_n;
wire    img_1_data_stream_1_V_write;
wire   [7:0] img_1_data_stream_1_V_dout;
wire    img_1_data_stream_1_V_empty_n;
wire    img_1_data_stream_1_V_read;
reg    ap_reg_procdone_image_filter_Block_proc_U0 = 1'b0;
reg    ap_sig_hs_done;
reg    ap_reg_procdone_image_filter_AXIvideo2Mat_U0 = 1'b0;
reg    ap_reg_procdone_image_filter_sobel_filter_core_U0 = 1'b0;
reg    ap_reg_procdone_image_filter_Mat2AXIvideo_U0 = 1'b0;
reg    ap_CS;
reg    ap_sig_top_allready;
reg    ap_reg_ready_image_filter_Block_proc_U0_ap_ready = 1'b0;
reg    ap_sig_ready_image_filter_Block_proc_U0_ap_ready;
reg    ap_sig_start_in_image_filter_Block_proc_U0_ap_start;
reg    ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready = 1'b0;
reg    ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready;
reg    ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start;
reg    ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready = 1'b0;
reg    ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready;
reg    ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start;


image_filter_CONTROL_BUS_s_axi #(
    .C_ADDR_WIDTH( C_S_AXI_CONTROL_BUS_ADDR_WIDTH ),
    .C_DATA_WIDTH( C_S_AXI_CONTROL_BUS_DATA_WIDTH ))
image_filter_CONTROL_BUS_s_axi_U(
    .AWVALID( s_axi_CONTROL_BUS_AWVALID ),
    .AWREADY( s_axi_CONTROL_BUS_AWREADY ),
    .AWADDR( s_axi_CONTROL_BUS_AWADDR ),
    .WVALID( s_axi_CONTROL_BUS_WVALID ),
    .WREADY( s_axi_CONTROL_BUS_WREADY ),
    .WDATA( s_axi_CONTROL_BUS_WDATA ),
    .WSTRB( s_axi_CONTROL_BUS_WSTRB ),
    .ARVALID( s_axi_CONTROL_BUS_ARVALID ),
    .ARREADY( s_axi_CONTROL_BUS_ARREADY ),
    .ARADDR( s_axi_CONTROL_BUS_ARADDR ),
    .RVALID( s_axi_CONTROL_BUS_RVALID ),
    .RREADY( s_axi_CONTROL_BUS_RREADY ),
    .RDATA( s_axi_CONTROL_BUS_RDATA ),
    .RRESP( s_axi_CONTROL_BUS_RRESP ),
    .BVALID( s_axi_CONTROL_BUS_BVALID ),
    .BREADY( s_axi_CONTROL_BUS_BREADY ),
    .BRESP( s_axi_CONTROL_BUS_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( image_filter_CONTROL_BUS_s_axi_U_ap_dummy_ce ),
    .rows( rows ),
    .cols( cols ),
    .ap_start( ap_start ),
    .interrupt( interrupt ),
    .ap_ready( ap_ready ),
    .ap_done( ap_done ),
    .ap_idle( ap_idle ),
    .C_XR0C0( C_XR0C0 ),
    .C_XR0C1( C_XR0C1 ),
    .C_XR0C2( C_XR0C2 ),
    .C_XR1C0( C_XR1C0 ),
    .C_XR1C1( C_XR1C1 ),
    .C_XR1C2( C_XR1C2 ),
    .C_XR2C0( C_XR2C0 ),
    .C_XR2C1( C_XR2C1 ),
    .C_XR2C2( C_XR2C2 ),
    .C_YR0C0( C_YR0C0 ),
    .C_YR0C1( C_YR0C1 ),
    .C_YR0C2( C_YR0C2 ),
    .C_YR1C0( C_YR1C0 ),
    .C_YR1C1( C_YR1C1 ),
    .C_YR1C2( C_YR1C2 ),
    .C_YR2C0( C_YR2C0 ),
    .C_YR2C1( C_YR2C1 ),
    .C_YR2C2( C_YR2C2 ),
    .c_high_thresh( c_high_thresh ),
    .c_low_thresh( c_low_thresh ),
    .c_invert( c_invert )
);

image_filter_Block_proc image_filter_Block_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_Block_proc_U0_ap_start ),
    .ap_done( image_filter_Block_proc_U0_ap_done ),
    .ap_continue( image_filter_Block_proc_U0_ap_continue ),
    .ap_idle( image_filter_Block_proc_U0_ap_idle ),
    .ap_ready( image_filter_Block_proc_U0_ap_ready ),
    .rows( image_filter_Block_proc_U0_rows ),
    .cols( image_filter_Block_proc_U0_cols ),
    .ap_return_0( image_filter_Block_proc_U0_ap_return_0 ),
    .ap_return_1( image_filter_Block_proc_U0_ap_return_1 ),
    .ap_return_2( image_filter_Block_proc_U0_ap_return_2 ),
    .ap_return_3( image_filter_Block_proc_U0_ap_return_3 )
);

image_filter_AXIvideo2Mat image_filter_AXIvideo2Mat_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_AXIvideo2Mat_U0_ap_start ),
    .ap_done( image_filter_AXIvideo2Mat_U0_ap_done ),
    .ap_continue( image_filter_AXIvideo2Mat_U0_ap_continue ),
    .ap_idle( image_filter_AXIvideo2Mat_U0_ap_idle ),
    .ap_ready( image_filter_AXIvideo2Mat_U0_ap_ready ),
    .video_in_TDATA( image_filter_AXIvideo2Mat_U0_video_in_TDATA ),
    .video_in_TVALID( image_filter_AXIvideo2Mat_U0_video_in_TVALID ),
    .video_in_TREADY( image_filter_AXIvideo2Mat_U0_video_in_TREADY ),
    .video_in_TKEEP( image_filter_AXIvideo2Mat_U0_video_in_TKEEP ),
    .video_in_TSTRB( image_filter_AXIvideo2Mat_U0_video_in_TSTRB ),
    .video_in_TUSER( image_filter_AXIvideo2Mat_U0_video_in_TUSER ),
    .video_in_TLAST( image_filter_AXIvideo2Mat_U0_video_in_TLAST ),
    .video_in_TID( image_filter_AXIvideo2Mat_U0_video_in_TID ),
    .video_in_TDEST( image_filter_AXIvideo2Mat_U0_video_in_TDEST ),
    .img_rows_V_read( image_filter_AXIvideo2Mat_U0_img_rows_V_read ),
    .img_cols_V_read( image_filter_AXIvideo2Mat_U0_img_cols_V_read ),
    .img_data_stream_0_V_din( image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din ),
    .img_data_stream_0_V_full_n( image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n ),
    .img_data_stream_0_V_write( image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write ),
    .img_data_stream_1_V_din( image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din ),
    .img_data_stream_1_V_full_n( image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n ),
    .img_data_stream_1_V_write( image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write )
);

image_filter_sobel_filter_core image_filter_sobel_filter_core_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_sobel_filter_core_U0_ap_start ),
    .ap_done( image_filter_sobel_filter_core_U0_ap_done ),
    .ap_continue( image_filter_sobel_filter_core_U0_ap_continue ),
    .ap_idle( image_filter_sobel_filter_core_U0_ap_idle ),
    .ap_ready( image_filter_sobel_filter_core_U0_ap_ready ),
    .src_data_stream_0_V_dout( image_filter_sobel_filter_core_U0_src_data_stream_0_V_dout ),
    .src_data_stream_0_V_empty_n( image_filter_sobel_filter_core_U0_src_data_stream_0_V_empty_n ),
    .src_data_stream_0_V_read( image_filter_sobel_filter_core_U0_src_data_stream_0_V_read ),
    .src_data_stream_1_V_dout( image_filter_sobel_filter_core_U0_src_data_stream_1_V_dout ),
    .src_data_stream_1_V_empty_n( image_filter_sobel_filter_core_U0_src_data_stream_1_V_empty_n ),
    .src_data_stream_1_V_read( image_filter_sobel_filter_core_U0_src_data_stream_1_V_read ),
    .dst_data_stream_0_V_din( image_filter_sobel_filter_core_U0_dst_data_stream_0_V_din ),
    .dst_data_stream_0_V_full_n( image_filter_sobel_filter_core_U0_dst_data_stream_0_V_full_n ),
    .dst_data_stream_0_V_write( image_filter_sobel_filter_core_U0_dst_data_stream_0_V_write ),
    .dst_data_stream_1_V_din( image_filter_sobel_filter_core_U0_dst_data_stream_1_V_din ),
    .dst_data_stream_1_V_full_n( image_filter_sobel_filter_core_U0_dst_data_stream_1_V_full_n ),
    .dst_data_stream_1_V_write( image_filter_sobel_filter_core_U0_dst_data_stream_1_V_write ),
    .rows( image_filter_sobel_filter_core_U0_rows ),
    .cols( image_filter_sobel_filter_core_U0_cols ),
    .C_XR0C0( image_filter_sobel_filter_core_U0_C_XR0C0 ),
    .C_XR0C1( image_filter_sobel_filter_core_U0_C_XR0C1 ),
    .C_XR0C2( image_filter_sobel_filter_core_U0_C_XR0C2 ),
    .C_XR1C0( image_filter_sobel_filter_core_U0_C_XR1C0 ),
    .C_XR1C1( image_filter_sobel_filter_core_U0_C_XR1C1 ),
    .C_XR1C2( image_filter_sobel_filter_core_U0_C_XR1C2 ),
    .C_XR2C0( image_filter_sobel_filter_core_U0_C_XR2C0 ),
    .C_XR2C1( image_filter_sobel_filter_core_U0_C_XR2C1 ),
    .C_XR2C2( image_filter_sobel_filter_core_U0_C_XR2C2 ),
    .C_YR0C0( image_filter_sobel_filter_core_U0_C_YR0C0 ),
    .C_YR0C1( image_filter_sobel_filter_core_U0_C_YR0C1 ),
    .C_YR0C2( image_filter_sobel_filter_core_U0_C_YR0C2 ),
    .C_YR1C0( image_filter_sobel_filter_core_U0_C_YR1C0 ),
    .C_YR1C1( image_filter_sobel_filter_core_U0_C_YR1C1 ),
    .C_YR1C2( image_filter_sobel_filter_core_U0_C_YR1C2 ),
    .C_YR2C0( image_filter_sobel_filter_core_U0_C_YR2C0 ),
    .C_YR2C1( image_filter_sobel_filter_core_U0_C_YR2C1 ),
    .c_high_thresh( image_filter_sobel_filter_core_U0_c_high_thresh ),
    .c_low_thresh( image_filter_sobel_filter_core_U0_c_low_thresh ),
    .c_invert( image_filter_sobel_filter_core_U0_c_invert )
);

image_filter_Mat2AXIvideo image_filter_Mat2AXIvideo_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_Mat2AXIvideo_U0_ap_start ),
    .ap_done( image_filter_Mat2AXIvideo_U0_ap_done ),
    .ap_continue( image_filter_Mat2AXIvideo_U0_ap_continue ),
    .ap_idle( image_filter_Mat2AXIvideo_U0_ap_idle ),
    .ap_ready( image_filter_Mat2AXIvideo_U0_ap_ready ),
    .img_rows_V_read( image_filter_Mat2AXIvideo_U0_img_rows_V_read ),
    .img_cols_V_read( image_filter_Mat2AXIvideo_U0_img_cols_V_read ),
    .img_data_stream_0_V_dout( image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_dout ),
    .img_data_stream_0_V_empty_n( image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n ),
    .img_data_stream_0_V_read( image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_read ),
    .img_data_stream_1_V_dout( image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_dout ),
    .img_data_stream_1_V_empty_n( image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n ),
    .img_data_stream_1_V_read( image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_read ),
    .video_out_TDATA( image_filter_Mat2AXIvideo_U0_video_out_TDATA ),
    .video_out_TVALID( image_filter_Mat2AXIvideo_U0_video_out_TVALID ),
    .video_out_TREADY( image_filter_Mat2AXIvideo_U0_video_out_TREADY ),
    .video_out_TKEEP( image_filter_Mat2AXIvideo_U0_video_out_TKEEP ),
    .video_out_TSTRB( image_filter_Mat2AXIvideo_U0_video_out_TSTRB ),
    .video_out_TUSER( image_filter_Mat2AXIvideo_U0_video_out_TUSER ),
    .video_out_TLAST( image_filter_Mat2AXIvideo_U0_video_out_TLAST ),
    .video_out_TID( image_filter_Mat2AXIvideo_U0_video_out_TID ),
    .video_out_TDEST( image_filter_Mat2AXIvideo_U0_video_out_TDEST )
);

FIFO_image_filter_img_0_rows_V_channel img_0_rows_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_rows_V_channel_U_ap_dummy_ce ),
    .if_write_ce( img_0_rows_V_channel_U_ap_dummy_ce ),
    .if_din( img_0_rows_V_channel_din ),
    .if_full_n( img_0_rows_V_channel_full_n ),
    .if_write( img_0_rows_V_channel_write ),
    .if_dout( img_0_rows_V_channel_dout ),
    .if_empty_n( img_0_rows_V_channel_empty_n ),
    .if_read( img_0_rows_V_channel_read )
);

FIFO_image_filter_img_0_cols_V_channel img_0_cols_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_cols_V_channel_U_ap_dummy_ce ),
    .if_write_ce( img_0_cols_V_channel_U_ap_dummy_ce ),
    .if_din( img_0_cols_V_channel_din ),
    .if_full_n( img_0_cols_V_channel_full_n ),
    .if_write( img_0_cols_V_channel_write ),
    .if_dout( img_0_cols_V_channel_dout ),
    .if_empty_n( img_0_cols_V_channel_empty_n ),
    .if_read( img_0_cols_V_channel_read )
);

FIFO_image_filter_img_1_rows_V img_1_rows_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_rows_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_rows_V_U_ap_dummy_ce ),
    .if_din( img_1_rows_V_din ),
    .if_full_n( img_1_rows_V_full_n ),
    .if_write( img_1_rows_V_write ),
    .if_dout( img_1_rows_V_dout ),
    .if_empty_n( img_1_rows_V_empty_n ),
    .if_read( img_1_rows_V_read )
);

FIFO_image_filter_img_1_cols_V img_1_cols_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_cols_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_cols_V_U_ap_dummy_ce ),
    .if_din( img_1_cols_V_din ),
    .if_full_n( img_1_cols_V_full_n ),
    .if_write( img_1_cols_V_write ),
    .if_dout( img_1_cols_V_dout ),
    .if_empty_n( img_1_cols_V_empty_n ),
    .if_read( img_1_cols_V_read )
);

FIFO_image_filter_img_0_data_stream_0_V img_0_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_0_V_din ),
    .if_full_n( img_0_data_stream_0_V_full_n ),
    .if_write( img_0_data_stream_0_V_write ),
    .if_dout( img_0_data_stream_0_V_dout ),
    .if_empty_n( img_0_data_stream_0_V_empty_n ),
    .if_read( img_0_data_stream_0_V_read )
);

FIFO_image_filter_img_0_data_stream_1_V img_0_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_1_V_din ),
    .if_full_n( img_0_data_stream_1_V_full_n ),
    .if_write( img_0_data_stream_1_V_write ),
    .if_dout( img_0_data_stream_1_V_dout ),
    .if_empty_n( img_0_data_stream_1_V_empty_n ),
    .if_read( img_0_data_stream_1_V_read )
);

FIFO_image_filter_img_1_data_stream_0_V img_1_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_1_data_stream_0_V_din ),
    .if_full_n( img_1_data_stream_0_V_full_n ),
    .if_write( img_1_data_stream_0_V_write ),
    .if_dout( img_1_data_stream_0_V_dout ),
    .if_empty_n( img_1_data_stream_0_V_empty_n ),
    .if_read( img_1_data_stream_0_V_read )
);

FIFO_image_filter_img_1_data_stream_1_V img_1_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_1_data_stream_1_V_din ),
    .if_full_n( img_1_data_stream_1_V_full_n ),
    .if_write( img_1_data_stream_1_V_write ),
    .if_dout( img_1_data_stream_1_V_dout ),
    .if_empty_n( img_1_data_stream_1_V_empty_n ),
    .if_read( img_1_data_stream_1_V_read )
);



/// ap_reg_procdone_image_filter_AXIvideo2Mat_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_AXIvideo2Mat_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_AXIvideo2Mat_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_AXIvideo2Mat_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_AXIvideo2Mat_U0_ap_done)) begin
            ap_reg_procdone_image_filter_AXIvideo2Mat_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_image_filter_Block_proc_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_Block_proc_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_Block_proc_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_Block_proc_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_Block_proc_U0_ap_done)) begin
            ap_reg_procdone_image_filter_Block_proc_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_image_filter_Mat2AXIvideo_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_Mat2AXIvideo_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_Mat2AXIvideo_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_Mat2AXIvideo_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_Mat2AXIvideo_U0_ap_done)) begin
            ap_reg_procdone_image_filter_Mat2AXIvideo_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_image_filter_sobel_filter_core_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_sobel_filter_core_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_sobel_filter_core_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_sobel_filter_core_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_sobel_filter_core_U0_ap_done)) begin
            ap_reg_procdone_image_filter_sobel_filter_core_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_top_allready))) begin
            ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_AXIvideo2Mat_U0_ap_ready)) begin
            ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_image_filter_Block_proc_U0_ap_ready assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_image_filter_Block_proc_U0_ap_ready
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_image_filter_Block_proc_U0_ap_ready <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_top_allready))) begin
            ap_reg_ready_image_filter_Block_proc_U0_ap_ready <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_Block_proc_U0_ap_ready)) begin
            ap_reg_ready_image_filter_Block_proc_U0_ap_ready <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_top_allready))) begin
            ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_sobel_filter_core_U0_ap_ready)) begin
            ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_0_cols_V_channel_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_0_cols_V_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_0_cols_V_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_proc_U0_ap_continue))) begin
            ap_reg_ready_img_0_cols_V_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_proc_U0_ap_done) & (ap_const_logic_1 == img_0_cols_V_channel_full_n))) begin
            ap_reg_ready_img_0_cols_V_channel_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_0_rows_V_channel_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_0_rows_V_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_0_rows_V_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_proc_U0_ap_continue))) begin
            ap_reg_ready_img_0_rows_V_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_proc_U0_ap_done) & (ap_const_logic_1 == img_0_rows_V_channel_full_n))) begin
            ap_reg_ready_img_0_rows_V_channel_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_1_cols_V_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_1_cols_V_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_1_cols_V_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_proc_U0_ap_continue))) begin
            ap_reg_ready_img_1_cols_V_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_proc_U0_ap_done) & (ap_const_logic_1 == img_1_cols_V_full_n))) begin
            ap_reg_ready_img_1_cols_V_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_1_rows_V_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_1_rows_V_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_1_rows_V_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_proc_U0_ap_continue))) begin
            ap_reg_ready_img_1_rows_V_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_proc_U0_ap_done) & (ap_const_logic_1 == img_1_rows_V_full_n))) begin
            ap_reg_ready_img_1_rows_V_full_n <= ap_const_logic_1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    ap_CS <= ap_const_logic_0;
end

/// ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel assign process. ///
always @ (image_filter_Block_proc_U0_ap_done or ap_reg_ready_img_0_cols_V_channel_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_0_cols_V_channel_full_n)) begin
        ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel = image_filter_Block_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel assign process. ///
always @ (image_filter_Block_proc_U0_ap_done or ap_reg_ready_img_0_rows_V_channel_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_0_rows_V_channel_full_n)) begin
        ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel = image_filter_Block_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V assign process. ///
always @ (image_filter_Block_proc_U0_ap_done or ap_reg_ready_img_1_cols_V_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_1_cols_V_full_n)) begin
        ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V = image_filter_Block_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V assign process. ///
always @ (image_filter_Block_proc_U0_ap_done or ap_reg_ready_img_1_rows_V_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_1_rows_V_full_n)) begin
        ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V = image_filter_Block_proc_U0_ap_done;
    end
end

/// ap_idle assign process. ///
always @ (image_filter_Block_proc_U0_ap_idle or image_filter_AXIvideo2Mat_U0_ap_idle or image_filter_sobel_filter_core_U0_ap_idle or image_filter_Mat2AXIvideo_U0_ap_idle or img_0_rows_V_channel_empty_n or img_0_cols_V_channel_empty_n or img_1_rows_V_empty_n or img_1_cols_V_empty_n)
begin
    if (((ap_const_logic_1 == image_filter_Block_proc_U0_ap_idle) & (ap_const_logic_1 == image_filter_AXIvideo2Mat_U0_ap_idle) & (ap_const_logic_1 == image_filter_sobel_filter_core_U0_ap_idle) & (ap_const_logic_1 == image_filter_Mat2AXIvideo_U0_ap_idle) & (ap_const_logic_0 == img_0_rows_V_channel_empty_n) & (ap_const_logic_0 == img_0_cols_V_channel_empty_n) & (ap_const_logic_0 == img_1_rows_V_empty_n) & (ap_const_logic_0 == img_1_cols_V_empty_n))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_sig_hs_done assign process. ///
always @ (image_filter_Mat2AXIvideo_U0_ap_done)
begin
    if ((ap_const_logic_1 == image_filter_Mat2AXIvideo_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

/// ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready assign process. ///
always @ (image_filter_AXIvideo2Mat_U0_ap_ready or ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready)
begin
    if ((ap_const_logic_0 == ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready)) begin
        ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready = image_filter_AXIvideo2Mat_U0_ap_ready;
    end else begin
        ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready = ap_const_logic_1;
    end
end

/// ap_sig_ready_image_filter_Block_proc_U0_ap_ready assign process. ///
always @ (image_filter_Block_proc_U0_ap_ready or ap_reg_ready_image_filter_Block_proc_U0_ap_ready)
begin
    if ((ap_const_logic_0 == ap_reg_ready_image_filter_Block_proc_U0_ap_ready)) begin
        ap_sig_ready_image_filter_Block_proc_U0_ap_ready = image_filter_Block_proc_U0_ap_ready;
    end else begin
        ap_sig_ready_image_filter_Block_proc_U0_ap_ready = ap_const_logic_1;
    end
end

/// ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready assign process. ///
always @ (image_filter_sobel_filter_core_U0_ap_ready or ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready)
begin
    if ((ap_const_logic_0 == ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready)) begin
        ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready = image_filter_sobel_filter_core_U0_ap_ready;
    end else begin
        ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_0_cols_V_channel_full_n assign process. ///
always @ (img_0_cols_V_channel_full_n or ap_reg_ready_img_0_cols_V_channel_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_0_cols_V_channel_full_n)) begin
        ap_sig_ready_img_0_cols_V_channel_full_n = img_0_cols_V_channel_full_n;
    end else begin
        ap_sig_ready_img_0_cols_V_channel_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_0_rows_V_channel_full_n assign process. ///
always @ (img_0_rows_V_channel_full_n or ap_reg_ready_img_0_rows_V_channel_full_n)
begin
    if ((ap_reg_ready_img_0_rows_V_channel_full_n == ap_const_logic_0)) begin
        ap_sig_ready_img_0_rows_V_channel_full_n = img_0_rows_V_channel_full_n;
    end else begin
        ap_sig_ready_img_0_rows_V_channel_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_1_cols_V_full_n assign process. ///
always @ (img_1_cols_V_full_n or ap_reg_ready_img_1_cols_V_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_1_cols_V_full_n)) begin
        ap_sig_ready_img_1_cols_V_full_n = img_1_cols_V_full_n;
    end else begin
        ap_sig_ready_img_1_cols_V_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_1_rows_V_full_n assign process. ///
always @ (img_1_rows_V_full_n or ap_reg_ready_img_1_rows_V_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_1_rows_V_full_n)) begin
        ap_sig_ready_img_1_rows_V_full_n = img_1_rows_V_full_n;
    end else begin
        ap_sig_ready_img_1_rows_V_full_n = ap_const_logic_1;
    end
end

/// ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start assign process. ///
always @ (ap_start or ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready)
begin
    if (((ap_const_logic_1 == ap_start) & (ap_const_logic_0 == ap_reg_ready_image_filter_AXIvideo2Mat_U0_ap_ready))) begin
        ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start = ap_const_logic_1;
    end else begin
        ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start = ap_const_logic_0;
    end
end

/// ap_sig_start_in_image_filter_Block_proc_U0_ap_start assign process. ///
always @ (ap_start or ap_reg_ready_image_filter_Block_proc_U0_ap_ready)
begin
    if (((ap_const_logic_0 == ap_reg_ready_image_filter_Block_proc_U0_ap_ready) & (ap_const_logic_1 == ap_start))) begin
        ap_sig_start_in_image_filter_Block_proc_U0_ap_start = ap_const_logic_1;
    end else begin
        ap_sig_start_in_image_filter_Block_proc_U0_ap_start = ap_const_logic_0;
    end
end

/// ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start assign process. ///
always @ (ap_start or ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready)
begin
    if (((ap_const_logic_1 == ap_start) & (ap_const_logic_0 == ap_reg_ready_image_filter_sobel_filter_core_U0_ap_ready))) begin
        ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start = ap_const_logic_1;
    end else begin
        ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start = ap_const_logic_0;
    end
end

/// ap_sig_top_allready assign process. ///
always @ (ap_sig_ready_image_filter_Block_proc_U0_ap_ready or ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready or ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready)
begin
    if (((ap_const_logic_1 == ap_sig_ready_image_filter_Block_proc_U0_ap_ready) & (ap_const_logic_1 == ap_sig_ready_image_filter_AXIvideo2Mat_U0_ap_ready) & (ap_const_logic_1 == ap_sig_ready_image_filter_sobel_filter_core_U0_ap_ready))) begin
        ap_sig_top_allready = ap_const_logic_1;
    end else begin
        ap_sig_top_allready = ap_const_logic_0;
    end
end

/// image_filter_Block_proc_U0_ap_continue assign process. ///
always @ (ap_sig_ready_img_0_rows_V_channel_full_n or ap_sig_ready_img_0_cols_V_channel_full_n or ap_sig_ready_img_1_rows_V_full_n or ap_sig_ready_img_1_cols_V_full_n)
begin
    if (((ap_const_logic_1 == ap_sig_ready_img_0_rows_V_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_img_0_cols_V_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_img_1_rows_V_full_n) & (ap_const_logic_1 == ap_sig_ready_img_1_cols_V_full_n))) begin
        image_filter_Block_proc_U0_ap_continue = ap_const_logic_1;
    end else begin
        image_filter_Block_proc_U0_ap_continue = ap_const_logic_0;
    end
end
assign ap_done = ap_sig_hs_done;
assign ap_ready = ap_sig_top_allready;

/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end
assign ap_sig_hs_continue = ap_const_logic_1;
assign image_filter_AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
assign image_filter_AXIvideo2Mat_U0_ap_start = (img_0_rows_V_channel_empty_n & img_0_cols_V_channel_empty_n & ap_sig_start_in_image_filter_AXIvideo2Mat_U0_ap_start);
assign image_filter_AXIvideo2Mat_U0_img_cols_V_read = img_0_cols_V_channel_dout;
assign image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n = img_0_data_stream_0_V_full_n;
assign image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n = img_0_data_stream_1_V_full_n;
assign image_filter_AXIvideo2Mat_U0_img_rows_V_read = img_0_rows_V_channel_dout;
assign image_filter_AXIvideo2Mat_U0_video_in_TDATA = video_in_TDATA;
assign image_filter_AXIvideo2Mat_U0_video_in_TDEST = video_in_TDEST;
assign image_filter_AXIvideo2Mat_U0_video_in_TID = video_in_TID;
assign image_filter_AXIvideo2Mat_U0_video_in_TKEEP = video_in_TKEEP;
assign image_filter_AXIvideo2Mat_U0_video_in_TLAST = video_in_TLAST;
assign image_filter_AXIvideo2Mat_U0_video_in_TSTRB = video_in_TSTRB;
assign image_filter_AXIvideo2Mat_U0_video_in_TUSER = video_in_TUSER;
assign image_filter_AXIvideo2Mat_U0_video_in_TVALID = video_in_TVALID;
assign image_filter_Block_proc_U0_ap_start = ap_sig_start_in_image_filter_Block_proc_U0_ap_start;
assign image_filter_Block_proc_U0_cols = cols;
assign image_filter_Block_proc_U0_rows = rows;
assign image_filter_CONTROL_BUS_s_axi_U_ap_dummy_ce = ap_const_logic_1;
assign image_filter_Mat2AXIvideo_U0_ap_continue = ap_sig_hs_continue;
assign image_filter_Mat2AXIvideo_U0_ap_start = (img_1_rows_V_empty_n & img_1_cols_V_empty_n);
assign image_filter_Mat2AXIvideo_U0_img_cols_V_read = img_1_cols_V_dout;
assign image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_dout = img_1_data_stream_0_V_dout;
assign image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n = img_1_data_stream_0_V_empty_n;
assign image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_dout = img_1_data_stream_1_V_dout;
assign image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n = img_1_data_stream_1_V_empty_n;
assign image_filter_Mat2AXIvideo_U0_img_rows_V_read = img_1_rows_V_dout;
assign image_filter_Mat2AXIvideo_U0_video_out_TREADY = video_out_TREADY;
assign image_filter_sobel_filter_core_U0_C_XR0C0 = C_XR0C0;
assign image_filter_sobel_filter_core_U0_C_XR0C1 = C_XR0C1;
assign image_filter_sobel_filter_core_U0_C_XR0C2 = C_XR0C2;
assign image_filter_sobel_filter_core_U0_C_XR1C0 = C_XR1C0;
assign image_filter_sobel_filter_core_U0_C_XR1C1 = C_XR1C1;
assign image_filter_sobel_filter_core_U0_C_XR1C2 = C_XR1C2;
assign image_filter_sobel_filter_core_U0_C_XR2C0 = C_XR2C0;
assign image_filter_sobel_filter_core_U0_C_XR2C1 = C_XR2C1;
assign image_filter_sobel_filter_core_U0_C_XR2C2 = C_XR2C2;
assign image_filter_sobel_filter_core_U0_C_YR0C0 = C_YR0C0;
assign image_filter_sobel_filter_core_U0_C_YR0C1 = C_YR0C1;
assign image_filter_sobel_filter_core_U0_C_YR0C2 = C_YR0C2;
assign image_filter_sobel_filter_core_U0_C_YR1C0 = C_YR1C0;
assign image_filter_sobel_filter_core_U0_C_YR1C1 = C_YR1C1;
assign image_filter_sobel_filter_core_U0_C_YR1C2 = C_YR1C2;
assign image_filter_sobel_filter_core_U0_C_YR2C0 = C_YR2C0;
assign image_filter_sobel_filter_core_U0_C_YR2C1 = C_YR2C1;
assign image_filter_sobel_filter_core_U0_ap_continue = ap_const_logic_1;
assign image_filter_sobel_filter_core_U0_ap_start = ap_sig_start_in_image_filter_sobel_filter_core_U0_ap_start;
assign image_filter_sobel_filter_core_U0_c_high_thresh = c_high_thresh;
assign image_filter_sobel_filter_core_U0_c_invert = c_invert;
assign image_filter_sobel_filter_core_U0_c_low_thresh = c_low_thresh;
assign image_filter_sobel_filter_core_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};
assign image_filter_sobel_filter_core_U0_dst_data_stream_0_V_full_n = img_1_data_stream_0_V_full_n;
assign image_filter_sobel_filter_core_U0_dst_data_stream_1_V_full_n = img_1_data_stream_1_V_full_n;
assign image_filter_sobel_filter_core_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};
assign image_filter_sobel_filter_core_U0_src_data_stream_0_V_dout = img_0_data_stream_0_V_dout;
assign image_filter_sobel_filter_core_U0_src_data_stream_0_V_empty_n = img_0_data_stream_0_V_empty_n;
assign image_filter_sobel_filter_core_U0_src_data_stream_1_V_dout = img_0_data_stream_1_V_dout;
assign image_filter_sobel_filter_core_U0_src_data_stream_1_V_empty_n = img_0_data_stream_1_V_empty_n;
assign img_0_cols_V_channel_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_cols_V_channel_din = image_filter_Block_proc_U0_ap_return_1;
assign img_0_cols_V_channel_read = image_filter_AXIvideo2Mat_U0_ap_ready;
assign img_0_cols_V_channel_write = ap_chn_write_image_filter_Block_proc_U0_img_0_cols_V_channel;
assign img_0_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_data_stream_0_V_din = image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din;
assign img_0_data_stream_0_V_read = image_filter_sobel_filter_core_U0_src_data_stream_0_V_read;
assign img_0_data_stream_0_V_write = image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write;
assign img_0_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_data_stream_1_V_din = image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din;
assign img_0_data_stream_1_V_read = image_filter_sobel_filter_core_U0_src_data_stream_1_V_read;
assign img_0_data_stream_1_V_write = image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write;
assign img_0_rows_V_channel_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_rows_V_channel_din = image_filter_Block_proc_U0_ap_return_0;
assign img_0_rows_V_channel_read = image_filter_AXIvideo2Mat_U0_ap_ready;
assign img_0_rows_V_channel_write = ap_chn_write_image_filter_Block_proc_U0_img_0_rows_V_channel;
assign img_1_cols_V_U_ap_dummy_ce = ap_const_logic_1;
assign img_1_cols_V_din = image_filter_Block_proc_U0_ap_return_3;
assign img_1_cols_V_read = image_filter_Mat2AXIvideo_U0_ap_ready;
assign img_1_cols_V_write = ap_chn_write_image_filter_Block_proc_U0_img_1_cols_V;
assign img_1_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
assign img_1_data_stream_0_V_din = image_filter_sobel_filter_core_U0_dst_data_stream_0_V_din;
assign img_1_data_stream_0_V_read = image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_read;
assign img_1_data_stream_0_V_write = image_filter_sobel_filter_core_U0_dst_data_stream_0_V_write;
assign img_1_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;
assign img_1_data_stream_1_V_din = image_filter_sobel_filter_core_U0_dst_data_stream_1_V_din;
assign img_1_data_stream_1_V_read = image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_read;
assign img_1_data_stream_1_V_write = image_filter_sobel_filter_core_U0_dst_data_stream_1_V_write;
assign img_1_rows_V_U_ap_dummy_ce = ap_const_logic_1;
assign img_1_rows_V_din = image_filter_Block_proc_U0_ap_return_2;
assign img_1_rows_V_read = image_filter_Mat2AXIvideo_U0_ap_ready;
assign img_1_rows_V_write = ap_chn_write_image_filter_Block_proc_U0_img_1_rows_V;
assign video_in_TREADY = image_filter_AXIvideo2Mat_U0_video_in_TREADY;
assign video_out_TDATA = image_filter_Mat2AXIvideo_U0_video_out_TDATA;
assign video_out_TDEST = image_filter_Mat2AXIvideo_U0_video_out_TDEST;
assign video_out_TID = image_filter_Mat2AXIvideo_U0_video_out_TID;
assign video_out_TKEEP = image_filter_Mat2AXIvideo_U0_video_out_TKEEP;
assign video_out_TLAST = image_filter_Mat2AXIvideo_U0_video_out_TLAST;
assign video_out_TSTRB = image_filter_Mat2AXIvideo_U0_video_out_TSTRB;
assign video_out_TUSER = image_filter_Mat2AXIvideo_U0_video_out_TUSER;
assign video_out_TVALID = image_filter_Mat2AXIvideo_U0_video_out_TVALID;


endmodule //image_filter

