// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_AXIvideo2Mat (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        video_in_TDATA,
        video_in_TVALID,
        video_in_TREADY,
        video_in_TKEEP,
        video_in_TSTRB,
        video_in_TUSER,
        video_in_TLAST,
        video_in_TID,
        video_in_TDEST,
        img_rows_V_read,
        img_cols_V_read,
        img_data_stream_0_V_din,
        img_data_stream_0_V_full_n,
        img_data_stream_0_V_write,
        img_data_stream_1_V_din,
        img_data_stream_1_V_full_n,
        img_data_stream_1_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 7'b1;
parameter    ap_ST_st2_fsm_1 = 7'b10;
parameter    ap_ST_st3_fsm_2 = 7'b100;
parameter    ap_ST_st4_fsm_3 = 7'b1000;
parameter    ap_ST_pp1_stg0_fsm_4 = 7'b10000;
parameter    ap_ST_st7_fsm_5 = 7'b100000;
parameter    ap_ST_st8_fsm_6 = 7'b1000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] video_in_TDATA;
input   video_in_TVALID;
output   video_in_TREADY;
input  [1:0] video_in_TKEEP;
input  [1:0] video_in_TSTRB;
input  [0:0] video_in_TUSER;
input  [0:0] video_in_TLAST;
input  [0:0] video_in_TID;
input  [0:0] video_in_TDEST;
input  [11:0] img_rows_V_read;
input  [11:0] img_cols_V_read;
output  [7:0] img_data_stream_0_V_din;
input   img_data_stream_0_V_full_n;
output   img_data_stream_0_V_write;
output  [7:0] img_data_stream_1_V_din;
input   img_data_stream_1_V_full_n;
output   img_data_stream_1_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg video_in_TREADY;
reg img_data_stream_0_V_write;
reg img_data_stream_1_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm = 7'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_26;
reg   [0:0] eol_1_reg_169;
reg   [15:0] axi_data_V_1_reg_180;
reg   [11:0] p_1_reg_191;
reg   [0:0] eol_reg_202;
reg   [0:0] axi_last_V_2_reg_214;
reg   [15:0] p_Val2_s_reg_226;
reg   [0:0] eol_2_reg_238;
reg    ap_sig_bdd_71;
reg   [15:0] tmp_data_V_reg_377;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_83;
reg   [0:0] tmp_last_V_reg_385;
wire   [0:0] exitcond1_fu_304_p2;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_97;
wire   [11:0] i_V_fu_309_p2;
reg   [11:0] i_V_reg_401;
wire   [0:0] exitcond2_fu_315_p2;
reg   [0:0] exitcond2_reg_406;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_4;
reg    ap_sig_bdd_108;
wire   [0:0] brmerge_fu_329_p2;
reg    ap_sig_bdd_116;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_sig_bdd_126;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
wire   [11:0] j_V_fu_320_p2;
wire   [7:0] tmp_42_fu_348_p1;
reg   [7:0] tmp_42_reg_419;
reg   [7:0] tmp_11_reg_424;
reg    ap_sig_cseq_ST_st7_fsm_5;
reg    ap_sig_bdd_149;
reg    ap_sig_bdd_154;
reg   [0:0] axi_last_V_3_reg_249;
reg   [0:0] axi_last_V1_reg_138;
reg    ap_sig_cseq_ST_st8_fsm_6;
reg    ap_sig_bdd_172;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_179;
reg   [15:0] axi_data_V_3_reg_261;
reg   [15:0] axi_data_V1_reg_148;
reg   [11:0] p_s_reg_158;
reg   [0:0] eol_1_phi_fu_172_p4;
reg   [15:0] axi_data_V_1_phi_fu_183_p4;
reg   [0:0] eol_phi_fu_206_p4;
wire   [0:0] ap_reg_phiprechg_axi_last_V_2_reg_214pp1_it0;
wire   [15:0] ap_reg_phiprechg_p_Val2_s_reg_226pp1_it0;
reg   [15:0] p_Val2_s_phi_fu_230_p4;
wire   [0:0] ap_reg_phiprechg_eol_2_reg_238pp1_it0;
wire   [0:0] axi_last_V_1_mux_fu_341_p2;
reg   [0:0] eol_3_reg_273;
reg   [0:0] sof_1_fu_90;
wire   [0:0] not_sof_2_fu_335_p2;
wire   [0:0] tmp_user_V_fu_295_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_sig_bdd_115;
reg    ap_sig_bdd_202;
reg    ap_sig_bdd_137;
reg    ap_sig_bdd_219;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond1_fu_304_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp1_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_fu_315_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond1_fu_304_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp1_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_fu_315_p2 == ap_const_lv1_0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond1_fu_304_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_fu_315_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_data_V1_reg_148 <= tmp_data_V_reg_377;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_data_V1_reg_148 <= axi_data_V_3_reg_261;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_reg_406 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        axi_data_V_1_reg_180 <= p_Val2_s_reg_226;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond1_fu_304_p2 == ap_const_lv1_0))) begin
        axi_data_V_1_reg_180 <= axi_data_V1_reg_148;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_fu_315_p2 == ap_const_lv1_0))) begin
        axi_data_V_3_reg_261 <= axi_data_V_1_phi_fu_183_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_3_reg_273) & ~ap_sig_bdd_154)) begin
        axi_data_V_3_reg_261 <= video_in_TDATA;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_last_V1_reg_138 <= tmp_last_V_reg_385;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_last_V1_reg_138 <= axi_last_V_3_reg_249;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_137) begin
        if (ap_sig_bdd_202) begin
            axi_last_V_2_reg_214 <= eol_1_phi_fu_172_p4;
        end else if (ap_sig_bdd_115) begin
            axi_last_V_2_reg_214 <= video_in_TLAST;
        end else if ((ap_true == ap_true)) begin
            axi_last_V_2_reg_214 <= ap_reg_phiprechg_axi_last_V_2_reg_214pp1_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_fu_315_p2 == ap_const_lv1_0))) begin
        axi_last_V_3_reg_249 <= eol_1_phi_fu_172_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_3_reg_273) & ~ap_sig_bdd_154)) begin
        axi_last_V_3_reg_249 <= video_in_TLAST;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_reg_406 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        eol_1_reg_169 <= axi_last_V_2_reg_214;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond1_fu_304_p2 == ap_const_lv1_0))) begin
        eol_1_reg_169 <= axi_last_V1_reg_138;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_137) begin
        if (ap_sig_bdd_202) begin
            eol_2_reg_238 <= axi_last_V_1_mux_fu_341_p2;
        end else if (ap_sig_bdd_115) begin
            eol_2_reg_238 <= video_in_TLAST;
        end else if ((ap_true == ap_true)) begin
            eol_2_reg_238 <= ap_reg_phiprechg_eol_2_reg_238pp1_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_fu_315_p2 == ap_const_lv1_0))) begin
        eol_3_reg_273 <= eol_phi_fu_206_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_3_reg_273) & ~ap_sig_bdd_154)) begin
        eol_3_reg_273 <= video_in_TLAST;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_reg_406 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        eol_reg_202 <= eol_2_reg_238;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond1_fu_304_p2 == ap_const_lv1_0))) begin
        eol_reg_202 <= ap_const_lv1_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_fu_315_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        p_1_reg_191 <= j_V_fu_320_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond1_fu_304_p2 == ap_const_lv1_0))) begin
        p_1_reg_191 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_137) begin
        if (ap_sig_bdd_202) begin
            p_Val2_s_reg_226 <= axi_data_V_1_phi_fu_183_p4;
        end else if (ap_sig_bdd_115) begin
            p_Val2_s_reg_226 <= video_in_TDATA;
        end else if ((ap_true == ap_true)) begin
            p_Val2_s_reg_226 <= ap_reg_phiprechg_p_Val2_s_reg_226pp1_it0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        p_s_reg_158 <= ap_const_lv12_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        p_s_reg_158 <= i_V_reg_401;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_fu_315_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        sof_1_fu_90 <= ap_const_lv1_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        sof_1_fu_90 <= ap_const_lv1_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        exitcond2_reg_406 <= exitcond2_fu_315_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i_V_reg_401 <= i_V_fu_309_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_fu_315_p2 == ap_const_lv1_0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        tmp_11_reg_424 <= {{p_Val2_s_phi_fu_230_p4[ap_const_lv32_F : ap_const_lv32_8]}};
        tmp_42_reg_419 <= tmp_42_fu_348_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(video_in_TVALID == ap_const_logic_0))) begin
        tmp_data_V_reg_377 <= video_in_TDATA;
        tmp_last_V_reg_385 <= video_in_TLAST;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or exitcond1_fu_304_p2 or ap_sig_cseq_ST_st4_fsm_3)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond1_fu_304_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (exitcond1_fu_304_p2 or ap_sig_cseq_ST_st4_fsm_3)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond1_fu_304_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp1_stg0_fsm_4 assign process. ///
always @ (ap_sig_bdd_108)
begin
    if (ap_sig_bdd_108) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_26)
begin
    if (ap_sig_bdd_26) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_83)
begin
    if (ap_sig_bdd_83) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_179)
begin
    if (ap_sig_bdd_179) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_97)
begin
    if (ap_sig_bdd_97) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_5 assign process. ///
always @ (ap_sig_bdd_149)
begin
    if (ap_sig_bdd_149) begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st8_fsm_6 assign process. ///
always @ (ap_sig_bdd_172)
begin
    if (ap_sig_bdd_172) begin
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_0;
    end
end

/// axi_data_V_1_phi_fu_183_p4 assign process. ///
always @ (axi_data_V_1_reg_180 or p_Val2_s_reg_226 or exitcond2_reg_406 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_reg_406 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        axi_data_V_1_phi_fu_183_p4 = p_Val2_s_reg_226;
    end else begin
        axi_data_V_1_phi_fu_183_p4 = axi_data_V_1_reg_180;
    end
end

/// eol_1_phi_fu_172_p4 assign process. ///
always @ (eol_1_reg_169 or axi_last_V_2_reg_214 or exitcond2_reg_406 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_reg_406 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        eol_1_phi_fu_172_p4 = axi_last_V_2_reg_214;
    end else begin
        eol_1_phi_fu_172_p4 = eol_1_reg_169;
    end
end

/// eol_phi_fu_206_p4 assign process. ///
always @ (eol_reg_202 or eol_2_reg_238 or exitcond2_reg_406 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_reg_406 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        eol_phi_fu_206_p4 = eol_2_reg_238;
    end else begin
        eol_phi_fu_206_p4 = eol_reg_202;
    end
end

/// img_data_stream_0_V_write assign process. ///
always @ (exitcond2_reg_406 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_116 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_126 or ap_reg_ppiten_pp1_it1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_reg_406 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        img_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        img_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// img_data_stream_1_V_write assign process. ///
always @ (exitcond2_reg_406 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_116 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_126 or ap_reg_ppiten_pp1_it1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_reg_406 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        img_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        img_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// p_Val2_s_phi_fu_230_p4 assign process. ///
always @ (video_in_TDATA or brmerge_fu_329_p2 or axi_data_V_1_phi_fu_183_p4 or ap_reg_phiprechg_p_Val2_s_reg_226pp1_it0 or ap_sig_bdd_219)
begin
    if (ap_sig_bdd_219) begin
        if (~(ap_const_lv1_0 == brmerge_fu_329_p2)) begin
            p_Val2_s_phi_fu_230_p4 = axi_data_V_1_phi_fu_183_p4;
        end else if ((ap_const_lv1_0 == brmerge_fu_329_p2)) begin
            p_Val2_s_phi_fu_230_p4 = video_in_TDATA;
        end else begin
            p_Val2_s_phi_fu_230_p4 = ap_reg_phiprechg_p_Val2_s_reg_226pp1_it0;
        end
    end else begin
        p_Val2_s_phi_fu_230_p4 = ap_reg_phiprechg_p_Val2_s_reg_226pp1_it0;
    end
end

/// video_in_TREADY assign process. ///
always @ (video_in_TVALID or ap_sig_cseq_ST_st2_fsm_1 or exitcond2_fu_315_p2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or brmerge_fu_329_p2 or ap_sig_bdd_116 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_126 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_st7_fsm_5 or ap_sig_bdd_154 or eol_3_reg_273)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(video_in_TVALID == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_3_reg_273) & ~ap_sig_bdd_154) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_fu_315_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_fu_329_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))))) begin
        video_in_TREADY = ap_const_logic_1;
    end else begin
        video_in_TREADY = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or video_in_TVALID or ap_sig_bdd_71 or exitcond1_fu_304_p2 or exitcond2_fu_315_p2 or ap_sig_bdd_116 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_126 or ap_reg_ppiten_pp1_it1 or ap_sig_bdd_154 or eol_3_reg_273 or tmp_user_V_fu_295_p1)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_71) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((~(video_in_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == tmp_user_V_fu_295_p1))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else if ((~(video_in_TVALID == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_user_V_fu_295_p1))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(exitcond1_fu_304_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_pp1_stg0_fsm_4 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_fu_315_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond2_fu_315_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_st7_fsm_5 : 
        begin
            if (((ap_const_lv1_0 == eol_3_reg_273) & ~ap_sig_bdd_154)) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else if ((~ap_sig_bdd_154 & ~(ap_const_lv1_0 == eol_3_reg_273))) begin
                ap_NS_fsm = ap_ST_st8_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end
        end
        ap_ST_st8_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_reg_phiprechg_axi_last_V_2_reg_214pp1_it0 = 'bx;
assign ap_reg_phiprechg_eol_2_reg_238pp1_it0 = 'bx;
assign ap_reg_phiprechg_p_Val2_s_reg_226pp1_it0 = 'bx;

/// ap_sig_bdd_108 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_108 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_115 assign process. ///
always @ (exitcond2_fu_315_p2 or brmerge_fu_329_p2)
begin
    ap_sig_bdd_115 = ((exitcond2_fu_315_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_fu_329_p2));
end

/// ap_sig_bdd_116 assign process. ///
always @ (video_in_TVALID or exitcond2_fu_315_p2 or brmerge_fu_329_p2)
begin
    ap_sig_bdd_116 = ((video_in_TVALID == ap_const_logic_0) & (exitcond2_fu_315_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_fu_329_p2));
end

/// ap_sig_bdd_126 assign process. ///
always @ (img_data_stream_0_V_full_n or img_data_stream_1_V_full_n or exitcond2_reg_406)
begin
    ap_sig_bdd_126 = (((img_data_stream_0_V_full_n == ap_const_logic_0) & (exitcond2_reg_406 == ap_const_lv1_0)) | ((exitcond2_reg_406 == ap_const_lv1_0) & (img_data_stream_1_V_full_n == ap_const_logic_0)));
end

/// ap_sig_bdd_137 assign process. ///
always @ (ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_116 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_126 or ap_reg_ppiten_pp1_it1)
begin
    ap_sig_bdd_137 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_126 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))));
end

/// ap_sig_bdd_149 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_149 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_154 assign process. ///
always @ (video_in_TVALID or eol_3_reg_273)
begin
    ap_sig_bdd_154 = ((video_in_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == eol_3_reg_273));
end

/// ap_sig_bdd_172 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_172 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_179 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_179 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_202 assign process. ///
always @ (exitcond2_fu_315_p2 or brmerge_fu_329_p2)
begin
    ap_sig_bdd_202 = ((exitcond2_fu_315_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == brmerge_fu_329_p2));
end

/// ap_sig_bdd_219 assign process. ///
always @ (exitcond2_fu_315_p2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it0)
begin
    ap_sig_bdd_219 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond2_fu_315_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0));
end

/// ap_sig_bdd_26 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_26 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_71 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_71 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_83 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_83 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_97 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_97 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end
assign axi_last_V_1_mux_fu_341_p2 = (eol_1_phi_fu_172_p4 | not_sof_2_fu_335_p2);
assign brmerge_fu_329_p2 = (sof_1_fu_90 | eol_phi_fu_206_p4);
assign exitcond1_fu_304_p2 = (p_s_reg_158 == img_rows_V_read? 1'b1: 1'b0);
assign exitcond2_fu_315_p2 = (p_1_reg_191 == img_cols_V_read? 1'b1: 1'b0);
assign i_V_fu_309_p2 = (p_s_reg_158 + ap_const_lv12_1);
assign img_data_stream_0_V_din = tmp_42_reg_419;
assign img_data_stream_1_V_din = tmp_11_reg_424;
assign j_V_fu_320_p2 = (p_1_reg_191 + ap_const_lv12_1);
assign not_sof_2_fu_335_p2 = (sof_1_fu_90 ^ ap_const_lv1_1);
assign tmp_42_fu_348_p1 = p_Val2_s_phi_fu_230_p4[7:0];
assign tmp_user_V_fu_295_p1 = video_in_TUSER;


endmodule //image_filter_AXIvideo2Mat

