#***************************************************************************
#
#   © Copyright 2013 Xilinx, Inc. All rights reserved. 
#
#   This file contains confidential and proprietary information of Xilinx,
#   Inc. and is protected under U.S. and international copyright and other
#   intellectual property laws. 
#
#   DISCLAIMER
#   This disclaimer is not a license and does not grant any rights to the
#   materials distributed herewith. Except as otherwise provided in a valid
#   license issued to you by Xilinx, and to the maximum extent permitted by
#   applicable law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH
#   ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS, 
#   EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES
#   OF MERCHANTABILITY, NON-INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR 
#   PURPOSE; and (2) Xilinx shall not be liable (whether in contract or 
#   tort, including negligence, or under any other theory of liability)
#   for any loss or damage of any kind or nature related to, arising under
#   or in connection with these materials, including for any direct, or any
#   indirect, special, incidental, or consequential loss or damage (including
#   loss of data, profits, goodwill, or any type of loss or damage suffered 
#   as a result of any action brought by a third party) even if such damage
#   or loss was reasonably foreseeable or Xilinx had been advised of the 
#   possibility of the same. 
#  
#   CRITICAL APPLICATIONS 
#   Xilinx products are not designed or intended to be fail-safe, or for use
#   in any application requiring fail-safe performance, such as life-support
#   or safety devices or systems, Class III medical devices, nuclear facilities,
#   applications related to the deployment of airbags, or any other applications
#   that could lead to death, personal injury, or severe property or environmental
#   damage (individually and collectively, "Critical Applications"). Customer
#   assumes the sole risk and liability of any use of Xilinx products in Critical
#   Applications, subject only to applicable laws and regulations governing 
#   limitations on product liability. 
#   
#   THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT 
#   ALL TIMES.
#
#***************************************************************************/

# All Target
all: boot elf
	@cp -rf $(TOP_DIR)/ready_to_test $(SD_DIR); \
        rm -f $(SD_DIR)/devicetree*; \
        cp -f $(TOP_DIR)/ready_to_test/$(DEVICE_TREE) $(SD_DIR)/devicetree.dtb; \
        cp -f $(BOOT_DIR)/BOOT.bin $(SD_DIR)/; \
        cp -f $(SW_DIR)/video_cmd/bin/video_cmd $(SD_DIR)/bin/; \
        chmod -R a+w $(SD_DIR); \
        echo "New sd_image is ready."

driver: core

elf: $(THIS_DIR)/$(SW_DIR)/video_cmd/bin/video_cmd

$(THIS_DIR)/$(SW_DIR)/video_cmd/bin/video_cmd: opencv_top.o top.o
	@cp -rL $(TOP_DIR)/$(SW_DIR)/$(SW_PATH) $(THIS_DIR)/$(SW_DIR); \
        cp -f $(THIS_DIR)/opencv_top.h $(SW_DIR)/video_lib/include/; \
        mv $(THIS_DIR)/*.o $(SW_DIR)/video_lib/lib/; \
        cp $(THIS_DIR)/v4l2_plugin.c $(SW_DIR)/video_lib/src/; \
        $(MAKE) -C $(SW_DIR)/video_lib/lib; \
        $(MAKE) -C $(SW_DIR)/video_cmd/bin

csim: $(DESIGN_FILES)
	@csim_flag=1 csynth_flag=0 cosim_flag=0 export_flag=0 $(VIVADO_HLS_CMD)

cosim: $(DESIGN_FILES)
	@csim_flag=0 csynth_flag=1 cosim_flag=1 export_flag=0 $(VIVADO_HLS_CMD)

core: $(HLS_PRJ)/solution1/impl/ip/$(IP_NAME).zip

$(HLS_PRJ)/solution1/impl/ip/$(IP_NAME).zip: $(DESIGN_FILES)
	@csim_flag=0 csynth_flag=1 cosim_flag=0 export_flag=1 $(VIVADO_HLS_CMD)

bitstream: $(THIS_DIR)/$(HW_DIR)/$(BITS_PATH)/system_top_wrapper.bit

$(THIS_DIR)/$(HW_DIR)/$(BITS_PATH)/system_top_wrapper.bit: $(HLS_PRJ)/solution1/impl/ip/$(IP_NAME).zip
	@cp -rf $(TOP_DIR)/$(HW_DIR) .; \
        chmod -R a+w $(HW_DIR); \
        rm -rf $(HW_DIR)/vivado/srcs/ip/*$(CORE_NAME)*; \
        cp -rf $(HLS_PRJ)/solution1/impl/ip $(HW_DIR)/vivado/srcs/ip/$(IP_NAME); \
        cd $(HW_DIR)/vivado; \
        rm -rf project; \
        $(VIVADO_CMD)

boot: $(THIS_DIR)/$(BOOT_DIR)/BOOT.bin

$(THIS_DIR)/$(BOOT_DIR)/BOOT.bin: $(THIS_DIR)/$(HW_DIR)/$(BITS_PATH)/system_top_wrapper.bit
	@cp -rL $(TOP_DIR)/$(SW_DIR)/$(BOOT_DIR) $(THIS_DIR)/$(BOOT_DIR); \
        chmod -R a+w $(BOOT_DIR); \
        cp -f $(THIS_DIR)/$(HW_DIR)/$(BITS_PATH)/system_top_wrapper.bit $(THIS_DIR)/$(BOOT_DIR)/; \
        cd $(BOOT_DIR); \
        ./bootgen.sh

xmd: bitstream elf
	@cp -rL $(TOP_DIR)/ready_to_test/$(XMD_DIR) .; \
	cp -f $(THIS_DIR)/$(HW_PRJ)/$(BITS_PATH)/system_top_wrapper.bit $(XMD_DIR)/; \
	cp -f $(THIS_DIR)/$(SW_DIR)/workspace/zvik_camera_bare_metal/Debug/zvik_camera_bare_metal.elf $(XMD_DIR)/; \
        echo "New standalone files are ready."

%.o: %.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Linux g++ compiler'
	arm-xilinx-linux-gnueabi-g++ -O3 -DHLS_NO_XIL_FPO_LIB -I$(ARM_OPENCV_FFMPEG)/include -I$(ARM_OPENCV_FFMPEG)/include/opencv -I$(AUTOESL_PATH) -c -fmessage-length=0 -fpermissive -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

help:
	@echo 'Makefile targets of XAPP1167 Reference Design:'; \
	echo '  make all        -- build sw and hw, generate sd_image'; \
	echo '  make csim       -- run C simulation'; \
	echo '  make cosim      -- run C/RTL co-simulation'; \
	echo '  make core       -- run high level synthesis and export ip'; \
	echo '  make bitstream  -- generate bitstream'; \
	echo '  make boot       -- generate boot image'; \
	echo '  make elf        -- build software'; \
	echo '  make clean      -- clean generated files of software'; \
	echo '  make allclean   -- clean all generated files'; \
	echo '  make help       -- give this help'; \
	echo ' '

clean:
	-$(RM) $(OBJS) $(BMPS) *.log $(DESIGN) $(SW_DIR)
	-@echo ' '

allclean:
	-$(RM) $(OBJS) $(BMPS) *.log $(DESIGN) $(HLS_PRJ) $(HW_DIR) $(BOOT_DIR) $(SD_DIR) $(SW_DIR) $(XMD_DIR)
	-@echo ' '

.PHONY: all clean dependents allclean help
.SECONDARY:

