// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// CONTROL_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x14 : Data signal of rows
//        bit 31~0 - rows[31:0] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of cols
//        bit 31~0 - cols[31:0] (Read/Write)
// 0x20 : reserved
// 0x24 : Data signal of C_XR0C0
//        bit 31~0 - C_XR0C0[31:0] (Read/Write)
// 0x28 : reserved
// 0x2c : Data signal of C_XR0C1
//        bit 31~0 - C_XR0C1[31:0] (Read/Write)
// 0x30 : reserved
// 0x34 : Data signal of C_XR0C2
//        bit 31~0 - C_XR0C2[31:0] (Read/Write)
// 0x38 : reserved
// 0x3c : Data signal of C_XR1C0
//        bit 31~0 - C_XR1C0[31:0] (Read/Write)
// 0x40 : reserved
// 0x44 : Data signal of C_XR1C1
//        bit 31~0 - C_XR1C1[31:0] (Read/Write)
// 0x48 : reserved
// 0x4c : Data signal of C_XR1C2
//        bit 31~0 - C_XR1C2[31:0] (Read/Write)
// 0x50 : reserved
// 0x54 : Data signal of C_XR2C0
//        bit 31~0 - C_XR2C0[31:0] (Read/Write)
// 0x58 : reserved
// 0x5c : Data signal of C_XR2C1
//        bit 31~0 - C_XR2C1[31:0] (Read/Write)
// 0x60 : reserved
// 0x64 : Data signal of C_XR2C2
//        bit 31~0 - C_XR2C2[31:0] (Read/Write)
// 0x68 : reserved
// 0x6c : Data signal of C_YR0C0
//        bit 31~0 - C_YR0C0[31:0] (Read/Write)
// 0x70 : reserved
// 0x74 : Data signal of C_YR0C1
//        bit 31~0 - C_YR0C1[31:0] (Read/Write)
// 0x78 : reserved
// 0x7c : Data signal of C_YR0C2
//        bit 31~0 - C_YR0C2[31:0] (Read/Write)
// 0x80 : reserved
// 0x84 : Data signal of C_YR1C0
//        bit 31~0 - C_YR1C0[31:0] (Read/Write)
// 0x88 : reserved
// 0x8c : Data signal of C_YR1C1
//        bit 31~0 - C_YR1C1[31:0] (Read/Write)
// 0x90 : reserved
// 0x94 : Data signal of C_YR1C2
//        bit 31~0 - C_YR1C2[31:0] (Read/Write)
// 0x98 : reserved
// 0x9c : Data signal of C_YR2C0
//        bit 31~0 - C_YR2C0[31:0] (Read/Write)
// 0xa0 : reserved
// 0xa4 : Data signal of C_YR2C1
//        bit 31~0 - C_YR2C1[31:0] (Read/Write)
// 0xa8 : reserved
// 0xac : Data signal of C_YR2C2
//        bit 31~0 - C_YR2C2[31:0] (Read/Write)
// 0xb0 : reserved
// 0xb4 : Data signal of c_high_thresh
//        bit 31~0 - c_high_thresh[31:0] (Read/Write)
// 0xb8 : reserved
// 0xbc : Data signal of c_low_thresh
//        bit 31~0 - c_low_thresh[31:0] (Read/Write)
// 0xc0 : reserved
// 0xc4 : Data signal of c_invert
//        bit 31~0 - c_invert[31:0] (Read/Write)
// 0xc8 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_CTRL            0x00
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_GIE                0x04
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_IER                0x08
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_ISR                0x0c
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_ROWS_DATA          0x14
#define XIMAGE_FILTER_CONTROL_BUS_BITS_ROWS_DATA          32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_COLS_DATA          0x1c
#define XIMAGE_FILTER_CONTROL_BUS_BITS_COLS_DATA          32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C0_DATA       0x24
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR0C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C1_DATA       0x2c
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR0C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C2_DATA       0x34
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR0C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C0_DATA       0x3c
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR1C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C1_DATA       0x44
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR1C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C2_DATA       0x4c
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR1C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C0_DATA       0x54
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR2C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C1_DATA       0x5c
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR2C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C2_DATA       0x64
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR2C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C0_DATA       0x6c
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR0C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C1_DATA       0x74
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR0C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C2_DATA       0x7c
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR0C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C0_DATA       0x84
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR1C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C1_DATA       0x8c
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR1C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C2_DATA       0x94
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR1C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C0_DATA       0x9c
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR2C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C1_DATA       0xa4
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR2C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C2_DATA       0xac
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR2C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_HIGH_THRESH_DATA 0xb4
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_HIGH_THRESH_DATA 32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_LOW_THRESH_DATA  0xbc
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_LOW_THRESH_DATA  32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_INVERT_DATA      0xc4
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_INVERT_DATA      32

