// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "ximage_filter.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XImage_filter_CfgInitialize(XImage_filter *InstancePtr, XImage_filter_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XImage_filter_Start(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XImage_filter_IsDone(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XImage_filter_IsIdle(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XImage_filter_IsReady(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XImage_filter_EnableAutoRestart(XImage_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XImage_filter_DisableAutoRestart(XImage_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XImage_filter_Set_rows(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XImage_filter_Get_rows(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XImage_filter_Set_cols(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XImage_filter_Get_cols(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XImage_filter_Set_C_XR0C0(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C0_DATA, Data);
}

u32 XImage_filter_Get_C_XR0C0(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C0_DATA);
    return Data;
}

void XImage_filter_Set_C_XR0C1(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C1_DATA, Data);
}

u32 XImage_filter_Get_C_XR0C1(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C1_DATA);
    return Data;
}

void XImage_filter_Set_C_XR0C2(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C2_DATA, Data);
}

u32 XImage_filter_Get_C_XR0C2(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C2_DATA);
    return Data;
}

void XImage_filter_Set_C_XR1C0(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C0_DATA, Data);
}

u32 XImage_filter_Get_C_XR1C0(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C0_DATA);
    return Data;
}

void XImage_filter_Set_C_XR1C1(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C1_DATA, Data);
}

u32 XImage_filter_Get_C_XR1C1(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C1_DATA);
    return Data;
}

void XImage_filter_Set_C_XR1C2(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C2_DATA, Data);
}

u32 XImage_filter_Get_C_XR1C2(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C2_DATA);
    return Data;
}

void XImage_filter_Set_C_XR2C0(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C0_DATA, Data);
}

u32 XImage_filter_Get_C_XR2C0(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C0_DATA);
    return Data;
}

void XImage_filter_Set_C_XR2C1(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C1_DATA, Data);
}

u32 XImage_filter_Get_C_XR2C1(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C1_DATA);
    return Data;
}

void XImage_filter_Set_C_XR2C2(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C2_DATA, Data);
}

u32 XImage_filter_Get_C_XR2C2(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C2_DATA);
    return Data;
}

void XImage_filter_Set_C_YR0C0(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C0_DATA, Data);
}

u32 XImage_filter_Get_C_YR0C0(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C0_DATA);
    return Data;
}

void XImage_filter_Set_C_YR0C1(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C1_DATA, Data);
}

u32 XImage_filter_Get_C_YR0C1(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C1_DATA);
    return Data;
}

void XImage_filter_Set_C_YR0C2(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C2_DATA, Data);
}

u32 XImage_filter_Get_C_YR0C2(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C2_DATA);
    return Data;
}

void XImage_filter_Set_C_YR1C0(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C0_DATA, Data);
}

u32 XImage_filter_Get_C_YR1C0(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C0_DATA);
    return Data;
}

void XImage_filter_Set_C_YR1C1(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C1_DATA, Data);
}

u32 XImage_filter_Get_C_YR1C1(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C1_DATA);
    return Data;
}

void XImage_filter_Set_C_YR1C2(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C2_DATA, Data);
}

u32 XImage_filter_Get_C_YR1C2(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C2_DATA);
    return Data;
}

void XImage_filter_Set_C_YR2C0(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C0_DATA, Data);
}

u32 XImage_filter_Get_C_YR2C0(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C0_DATA);
    return Data;
}

void XImage_filter_Set_C_YR2C1(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C1_DATA, Data);
}

u32 XImage_filter_Get_C_YR2C1(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C1_DATA);
    return Data;
}

void XImage_filter_Set_C_YR2C2(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C2_DATA, Data);
}

u32 XImage_filter_Get_C_YR2C2(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C2_DATA);
    return Data;
}

void XImage_filter_Set_c_high_thresh(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_HIGH_THRESH_DATA, Data);
}

u32 XImage_filter_Get_c_high_thresh(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_HIGH_THRESH_DATA);
    return Data;
}

void XImage_filter_Set_c_low_thresh(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_LOW_THRESH_DATA, Data);
}

u32 XImage_filter_Get_c_low_thresh(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_LOW_THRESH_DATA);
    return Data;
}

void XImage_filter_Set_c_invert(XImage_filter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_INVERT_DATA, Data);
}

u32 XImage_filter_Get_c_invert(XImage_filter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_C_INVERT_DATA);
    return Data;
}

void XImage_filter_InterruptGlobalEnable(XImage_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_GIE, 1);
}

void XImage_filter_InterruptGlobalDisable(XImage_filter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_GIE, 0);
}

void XImage_filter_InterruptEnable(XImage_filter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_IER);
    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XImage_filter_InterruptDisable(XImage_filter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_IER);
    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XImage_filter_InterruptClear(XImage_filter *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_filter_WriteReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XImage_filter_InterruptGetEnabled(XImage_filter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_IER);
}

u32 XImage_filter_InterruptGetStatus(XImage_filter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XImage_filter_ReadReg(InstancePtr->Control_bus_BaseAddress, XIMAGE_FILTER_CONTROL_BUS_ADDR_ISR);
}

