//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? 3? 16 2016 10:57:44
//
//      Input file      : 
//      Component name  : morph_open_2d
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


	module Morph_Open_2D(
		din,//输入数据流
		dout_valid,//输出数据有效
		dout,//输出数据流 
		rst_n,//异步复位信号
		din_valid,//输入有效信号 
		dbg_vsync, 
		dbg_out, 
		dbg_valid, 
		vsync,//输入场同步信号 
		vsync_out,//输出场同步信号 
		clk//同步时钟信号
	);
	
	parameter       DW = 14;//数据位宽
	parameter       KSZ = 7;//处理尺寸
	parameter       IW = 640;//图像宽度
	parameter       IH = 512;//图像高度
	input [DW-1:0]  din;
	output          dout_valid;
	output [DW-1:0] dout;
	input           rst_n;
	input           din_valid;
	output          dbg_vsync;
	output [DW-1:0] dbg_out;
	output          dbg_valid;
	input           vsync;
	output          vsync_out;
	input           clk;
   
   
	wire            erode_valid;
	wire            erode_vsync;
	wire [DW-1:0]   dout_erode;

	wire            dout_valid_tmp1;
	wire            vsync_out_tmp1;
	wire [DW-1:0]   dout_data_tmp1;

	assign dout_valid = dout_valid_tmp1;
	assign dout = dout_data_tmp1;
	assign vsync_out = vsync_out_tmp1;

	assign dbg_out = dout_erode;
	assign dbg_valid = erode_valid;
	assign dbg_vsync = erode_vsync;
   
  //首先进行腐蚀操作
  Morph_2D #(DW, KSZ, IH, IW, 1)
		morph_erode(
			.rst_n(rst_n), 
			.clk(clk), 
			.din_valid(din_valid), 
			.din(din), 
			.dout(dout_erode), 
			.vsync(vsync), 
			.vsync_out(erode_vsync), 
			.dout_valid(erode_valid)
		);
  //接着进行膨胀操作 
  Morph_2D #(DW, KSZ, IH, IW, 0)
		morph_dilate(
			.rst_n(rst_n), 
			.clk(clk),
			.din_valid(erode_valid),
			.din(dout_erode),
			.dout(dout_data_tmp1),
			.vsync(erode_vsync), 
			.vsync_out(vsync_out_tmp1),
			.dout_valid(dout_valid_tmp1)
		);
   
endmodule


