set_property PACKAGE_PIN V1 [get_ports strtstop] 
set_property PACKAGE_PIN R15 [get_ports reset] 
set_property PACKAGE_PIN P17 [get_ports clk] 
set_property PACKAGE_PIN U4 [get_ports mode] 
set_property PACKAGE_PIN R11 [get_ports lap_load] 

set_property IOSTANDARD LVCMOS33 [get_ports strtstop]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports mode]
set_property IOSTANDARD LVCMOS33 [get_ports lap_load]

set_property PACKAGE_PIN G6 [get_ports {out_c[0]}] 
set_property PACKAGE_PIN E1 [get_ports {out_c[1]}] 
set_property PACKAGE_PIN F1 [get_ports {out_c[2]}] 
set_property PACKAGE_PIN G1 [get_ports {out_c[3]}] 
set_property PACKAGE_PIN H1 [get_ports {out_c[4]}] 

set_property IOSTANDARD LVCMOS33 [get_ports {out_c[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_c[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_c[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_c[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_c[4]}] 

set_property PACKAGE_PIN B4 [get_ports {out_m[0]}] 
set_property PACKAGE_PIN A4 [get_ports {out_m[1]}] 
set_property PACKAGE_PIN A3 [get_ports {out_m[2]}] 
set_property PACKAGE_PIN B1 [get_ports {out_m[3]}] 
set_property PACKAGE_PIN A1 [get_ports {out_m[4]}] 
set_property PACKAGE_PIN B3 [get_ports {out_m[5]}] 
set_property PACKAGE_PIN B2 [get_ports {out_m[6]}] 
set_property PACKAGE_PIN D5 [get_ports {out_m[7]}] 

set_property IOSTANDARD LVCMOS33 [get_ports {out_m[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_m[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_m[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_m[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_m[4]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_m[5]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_m[6]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_m[7]}]

set_property PACKAGE_PIN D4 [get_ports {out_s[0]}] 
set_property PACKAGE_PIN E3 [get_ports {out_s[1]}] 
set_property PACKAGE_PIN D3 [get_ports {out_s[2]}] 
set_property PACKAGE_PIN F4 [get_ports {out_s[3]}] 
set_property PACKAGE_PIN F3 [get_ports {out_s[4]}] 
set_property PACKAGE_PIN E2 [get_ports {out_s[5]}] 
set_property PACKAGE_PIN D2 [get_ports {out_s[6]}] 
set_property PACKAGE_PIN H2 [get_ports {out_s[7]}] 

set_property IOSTANDARD LVCMOS33 [get_ports {out_s[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_s[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_s[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_s[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_s[4]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_s[5]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_s[6]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {out_s[7]}]
